### ISSUE TITLE
PLAN view of map on state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#101]
Per #94, when a Plan is selected, the results map will need to display differently:

* Districts that are always R are red
* Districts that are always D are blue
* Districts that go both ways are hashed red and blue.

Probably needs to be considered in light of #95 

And will likely result in a new data deliverable per #67

**Comment by gregallensworth** [comment]
As of yesterday, this is implemented in #67 though there may be some fine-tuning of the colors and opacities and the hash image-fill.

**Comment by danrademacher** [comment]
Per discussion on Tuesday, we need to try a version of the BOTH png without the white, for a less shimmering barber-pole effect

**Comment by tsinn** [comment]
new
![image](https://user-images.githubusercontent.com/881970/35069250-a4be27ac-fba7-11e7-814c-764d3b693b36.png)

**Comment by tsinn** [comment]
![image](https://user-images.githubusercontent.com/881970/35069887-84340298-fba9-11e7-9333-9c63da587969.png)
