### ISSUE TITLE
Secure remaining tabular metric data (State Senate, some State House)

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#105]
Status of tabular data:
- [x] US Congress complete for 25 states and we assume this is it.
- [x] State House partial for 39 states, missing all Wasted Vote and seat counts. These may or may not be obtainable.
- [x] State Senate, completely absent.

@migurski has been working on this. Logging here to track among our other key TODOs

**Comment by migurski** [comment]
[State Senate data is now here](https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=7069460) (`chamber` = 1 rows highlighted in yellow).

It has some limitations compared to the state house data:
- Of the three metrics, only EG has been calculated
- Generally only available for the past two redistricting cycles

**Comment by danrademacher** [comment]
OK, I translated this into a production table with expected schema:
https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=317626967

One key difference here (beyond missing data) is the issue that for US House and State House tables, each row is an election, which shows only plan-level data. 

We might need to create rows for each election, so that the plan picker works. But first let's try it with this data and see if it "just works"

Still TODO, as part of #212, is generating State Senate curve images.

**Comment by danrademacher** [comment]
State Senate curve for EG:
[statesenate_eg_plan_curve.svg.zip](https://github.com/PlanScore/PlanScore/files/1722016/statesenate_eg_plan_curve.svg.zip)

+/- is 22%

Note that we have ONLY Efficiency Gap for State Senate, no PB or MMD, so those'll just be "no data" conditions.

**Comment by danrademacher** [comment]
Replacing this with a clearer implementation issue in #216
