### ISSUE TITLE
Secure election returns data for State House and Senate

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#106]
We currently have election return data [for US House](https://docs.google.com/spreadsheets/d/1UkXOOXGLSoRjvpGj1eI5oTaMMIbo8jdevLzbDGuUU0E/edit#gid=1870149967). Also needed for maps on state pages:
- [ ] State Senate
- [ ] State House

Or if we can't have that, then we just show geometry, though user interviews show strong desire to see results on the ground.

**Comment by migurski** [comment]
This might be one to close?
