### ISSUE TITLE
Timeline display bug in Safari for Mac

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#109]
Looks like this in Safari 10.1.1:

<img width="1169" alt="screen shot 2017-12-31 at 9 24 22 am" src="https://user-images.githubusercontent.com/58730/34463304-736d88da-ee0c-11e7-87d9-a74ed0149d48.png">

**Comment by migurski** [comment]
I am no longer seeing this behavior in Safari.

**Comment by danrademacher** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/1423200/34527290-f89d287c-f059-11e7-8b90-5a1d11d5f4a9.png)

And in FF:
![image](https://user-images.githubusercontent.com/1423200/34527316-1595cb3c-f05a-11e7-8b24-7036952e72f5.png)

Edge:
![image](https://user-images.githubusercontent.com/1423200/34527416-55cb5c30-f05a-11e7-8a1d-53438dbd83c8.png)
