### ISSUE TITLE
Sentence about Plans and Elections no longer appearing

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#111]
Looks like our "TRUE" condition is never getting called properly:
![screen shot 2018-01-01 at 2 12 56 pm](https://user-images.githubusercontent.com/1423200/34471415-e37a4702-eefd-11e7-9fce-fcb65eebf1b3.png)

But it was working before Christmas.

Related to #72

**Comment by gregallensworth** [comment]
Fixed the `hasdata-thisyear` logic as needed.
