### ISSUE TITLE
Disable State Senate button in geog picker

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#112]
Pending #105 and doubt about getting that data, disable the button and add a tooltip that says "We're working on getting State Senate data. Stay tuned!"

**Comment by gregallensworth** [comment]
Note that adding a `title` property to create a tooltip, will be ineffective on mobile.

**Comment by gregallensworth** [comment]
Done, on both State and Home pages.

* Added a visual style: some opacity and a not-allowed cursor.  This should make it visually clear that these are known to be broken.
* Added behavior: click on *statesentate* will `alert()` a popup saying to stay tuned.

**Comment by gregallensworth** [comment]
Let's leave this open as a reminder when #105 is completed, to re-enable these.
* home page, click behavior in selectBoundaryType()
* state page, click behavior in selectBoundaryType()
* home page CSS for this button
* state page CSS for this button
* as well as making it actually load the data properly

**Comment by gregallensworth** [comment]
MM wants the behavior changed, as he does not like the `alert()`

Instead, see about faking a get-zero-rows condition, and/or handle a 404 on the `bias_statesenate.csv` file as effectively being the same as a zero-rows condition, so as to trigger the usual "we have no data for this state for this district level" condition (*hasdata-atall*)

**Comment by gregallensworth** [comment]
5117045 for state pages, 416c39c for front page

Selecting State Senate now resumes normal behavior: tries to download the CSV, finds 0 matching rows, and proceeds in the usual fashion. That is, on the front page a blank map and all-white swatches in the states listing, and on state pages the "this state has no info for this district type" message.

When the real data roll around, we will still want to remove the cosmetic styling warning folks against the State Senate (opacity, cursor) and of course test that the data work as expected.

**Comment by migurski** [comment]
Normal behavior sounds right to me. Paired with GA events and a working URL hash, this’ll allow us to offer messaging like “no data for now, check back later”.

**Comment by gregallensworth** [comment]
Commit adfe9bb on branch `gda-216_112-statesenate` removes the special styling. "State Senates" buttons on front page and state pages, are now visible at 4/12ths width, and no longer have the opacity & cursor styling. They're just like the other two.

Now onward to #216 in which we add data to make State Senates work.
