### ISSUE TITLE
Clicking on a state on the home page always links to latest election

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#115]
When clicking on a state on the homepage, the modal link to the state page does not appear to respect the selected election year, and always links to 2016.

**Comment by gregallensworth** [comment]
Ideally, this would apply to the states list as well as the Learn More link in the popups.

In all cases, the hyperlinks should be modified to include the `#YYYY-type-plan` hash component.

- [ ] Learn More link in state info
- [ ] States listing down below
