### ISSUE TITLE
Static content for /efficiencygap, /meanmedian, /partisanbias

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#117]
These pages need copy:
- [ ] https://planscore.org/efficiencygap/
- [ ] https://planscore.org/meanmedian/
- [ ] https://planscore.org/partisanbias/

Can be dropped directly into these pages as HTML or, maybe easier, in a gDoc that non-devs can chime in on.

Here's a gDoc we can use: https://docs.google.com/document/d/1iIjfLkfixZ6JZPDziAbFd9W4br2fXa87qJHZzFgqvOE/edit#

**Comment by migurski** [comment]
I wrote <150 word summaries for each of the metrics in the document above, and for now simply repeated them in the 500 word section.
