### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#119]
broken links currently go to a “403 Forbidden” rather than a 404 page. Seems undesirable in that (a) the site seems more broken than a 4904 and (b) we can't redirect people via a custom 404.

Easy for us to make one, if we have method to route to one. @migurski is this something easily set up via cloudfront if we make `planscore.org/404` a page?

**Comment by migurski** [comment]
I believe that if you create something called `error.html`, Cloudfront will automagically use it as a 404 page.

**Comment by danrademacher** [comment]
I'll move this over to @gregallensworth who has some time. Greg, I wasn't sure how to put an arbitrary `error.html` at root of our static site in a way that's most friendly to build process.

**Comment by gregallensworth** [comment]
This new page is in the site and build system as usual:  `error.js6 error.src.html  error.scss`

The page is visible here:  https://planscore.org/error.html

There may be more configuration necessary at Cloudfront to use this as an effective 404 page:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/custom-error-pages.html
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/HTTPStatusCodes.html#HTTPStatusCodes-custom-error-pages

When this is done, it **may be necessary** to rework some of the CSV and TopoJSON programming,. When a CSV file or TopoJSON file is not found (404) that is handled as a missing-data condition. Depending on whether Cloudfront sends a proper 404 response in addition to this visible HTML, these AJAX calls may no longer get a 404 but a HTML page, and need reconfiguration to deal with this error mode.

**Comment by migurski** [comment]
This is now in place:

```
> curl -i https://planscore.org/nobody-here -s | head

HTTP/1.1 404 Not Found
Content-Type: text/html
Content-Length: 4652
…
```
