### ISSUE TITLE
Make "More biased than" statement on home match statepage

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#122]
The second sentence of the home page popup here:
![image](https://user-images.githubusercontent.com/1423200/34547297-f4ee7ece-f0ae-11e7-9a40-1be0940de4f5.png)

Should be same as the sentence for `eg_avg` on the state page, as modified in #121

**Comment by danrademacher** [comment]
Wording is good, but the data showing is different.

Home page says NC2016 is more biased than 50% of plans:
![image](https://user-images.githubusercontent.com/1423200/34547974-d2b92674-f0b3-11e7-9ccf-a032e96c656d.png)

But state page correctly shows that it's more biased than 99% of plans we've analyzed:
![image](https://user-images.githubusercontent.com/1423200/34547983-e88ff7e8-f0b3-11e7-8556-e07a4b0c5331.png)

Looks like the home page is doing some math that's not quite working, while the state page is using `eg_avg_percentrank` from the CSV, which should be correct.

**Comment by gregallensworth** [comment]
The state-info popup has been reworked, to use the specified field: `eg_avg_percentrank`

This was the only use of `lookupBiasPercentile()` therefore lookupBiasPercentile() has been removed as well. This was imported into the state pages though later not used, so has been removed from those pages as well.
