### ISSUE TITLE
Consider better display of balanced plans

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#123]
Biased plans are looking really sharp, with clear display of metrics and Red/Blue valence.

Balanced plans are looking plain:
![image](https://user-images.githubusercontent.com/1423200/34547783-80810ff8-f0b2-11e7-85f2-bec06132b0ef.png)

Here's an example:
https://planscore.org/north_carolina/#!1998-plan-ushouse

Adding unbiased-purple boxes to the tabs and the metric readouts (which currently don't show) would make a lot of sense. Could be a deep purple from the logo.

But what's the letter in the tab box and what's the wording?

Like this maybe?
![image](https://user-images.githubusercontent.com/1423200/34547895-3ea16726-f0b3-11e7-8c93-53e994186e7e.png)

The "B" is weird on its own...

**Comment by danrademacher** [comment]
Let's find out what @migurski thinks!

**Comment by migurski** [comment]
The purple doesn't really work for this — lots of color blindness issues and it seems too dramatic a color to indicate balance. I would choose gray. The “B” should maybe be omitted entirely?

**Comment by danrademacher** [comment]
Roger that, like so:
![image](https://user-images.githubusercontent.com/1423200/34548427-ed1e8f42-f0b6-11e7-9d78-f9ac2f79fa3c.png)

But maybe it makes sense to have the gray box with metric but nothing in the tab, liks this:
![image](https://user-images.githubusercontent.com/1423200/34548449-038e1072-f0b7-11e7-828c-d060bdec0e7e.png)

Otherwise I think the gray in the tab might look broken, like it's missing something

**Comment by migurski** [comment]
Yeah, that second example looks good to me. At most I’d put a ✅ up there?

**Comment by gregallensworth** [comment]
2167aa5 instates the *metricdrsum* box, even in the event of a balanced plan. This is implemented per second example above:
* Within the tab: "X% Balanced" with a grey background
* In the tab: nothing
