### ISSUE TITLE
Sometimes, the wasted votes chart is too big

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#124]
I've seen this a twice now, so maybe not a total aberration:
![image](https://user-images.githubusercontent.com/1423200/34550113-11d47ae8-f0c3-11e7-9190-ec6d17e2010b.png)

But can't see the pattern. Seems like as soon as I refresh or even change window size, the chart snaps into place.

**Comment by gregallensworth** [comment]
ab6e6fa  The wasted votes chart now uses a fixed width of `300px` rather than `100%` to fit the dynamic-width cell. As with the bellcurve charts yesterday, the dynamic width Just Doesn't Work Well and a fixed size is reliable.
