### ISSUE TITLE
Remove use of JS popups for missing data

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#125]
Clicking on [State House when data does not exist](https://planscore.org/missouri/#!2016-election-statehouse) brings up regular HTML with the words “No plan data are available for the selected year for this district type.” Clicking on State Senate instead brings up a Javascript alert box. Can that be changed to behave like State House?

Connected question: what events would be sent to Google Analytics when interacting with a state page?

**Comment by gregallensworth** [comment]
See issue #112   The request was to temporarily disable all State Senate functionality, on grounds that we do not have the data and may not for quite some time. As such, this should be taken up in issue 112.
