### ISSUE TITLE
Add Upload Plan block to sidebar on state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#128]
Styled already at `/patternlibrary`
![image](https://user-images.githubusercontent.com/1423200/34582454-b131a32e-f148-11e7-8328-805931ddf998.png)

Just needs to find a home under the left sidebar on statebar, per Xd designs.

**Comment by tsinn** [comment]
In `_statetemplate` `state_template.src`, goes beneath
`<div class="hidden-xs row" id="yearpicker-big"></div>`
but I think it needs to be added programmatically because of the State Name

Basic HTML is
```
<div class="gray">
                <p>New Plans</p>
                <span>Drawing your own district map of North Carolina? Upload it here to find out how well it scores on these and other measures.</span>
                <button class="btn btn-default" >Upload Plan</button>
            </div>
```
