### ISSUE TITLE
Mobile version of plan/election picker, plus related changes

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#129]
Based on notes from conversation with Mike today:

1. On Mobile, view is EITHER election or plan, so we have only one forward/next control for one or the other.
2. On both mobile and desktop, the TITLE of the page is _either_ PLAN NAME or ELECTION NAME, not both as I had thought in #94 
3. Then copy at the top includes text with links to get between PLAN and ELECTION, like so:
*  viewing a PLAN, "This plan covered the [year](), [year](), and [year]() elections." 
* viewing an ELECTION, "This election was part of the [year-year plan]()"

This is actually pretty simple. Not sure why it took me so long to wrap my head around it!

**Comment by danrademacher** [comment]
So we need a design of a forward/next control that can accommodate names like "2012-2016 Plan" and have big hit areas for scrolling through. I assume it should be full-width on narrow screens.

**Comment by danrademacher** [comment]
And then once we have an election forward/next design, that becomes the year picker on home page.

**Comment by danrademacher** [comment]
Something like this:

PLAN
![image](https://user-images.githubusercontent.com/1423200/34620882-ddd963ae-f1fb-11e7-99d8-35de0f1ca97d.png)

ELECTION
![image](https://user-images.githubusercontent.com/1423200/34620928-03dff0b8-f1fc-11e7-81f2-0fe9fe900566.png)

Seems like we might also be able to just hide the `<h1>` title here on mobile and treat the picker as the title, moving more stuff above the fold.

**Comment by danrademacher** [comment]
And the links and wording could be the same on desktop and mobile. Doesn't hurt to have those links even if picking either plan or election is already easy on desktop.

**Comment by tsinn** [comment]
Not sure what to do in terms of showing Plan OR Election. Not sure which is more relevant? I'd guess Plan is more relevant and Election is more granular, suggesting we should go with just Plans. Also, I agree that the `<h1>` title should be hidden on mobile, leaving the picker as the title. As far as design, I like what you have here, and I would just do minor CSS tweaks afterwards. Assign to Greg at this point?

**Comment by danrademacher** [comment]
Concept is if you have a plan selected, that shows. If you have an election, that shows

**Comment by migurski** [comment]
Some input from Nick that might simplify this somewhat:

- The volatility from year to year is a significant problem.
- We want to encourage people to think about plans in their entirety, which aggregate data encourages but year-by-year data works against.

If the election-level volatility obscures the overall plan-level message, then it might make sense to step back from my suggestion of plan and state elections to focus solely on plans.

**Comment by danrademacher** [comment]
Given https://github.com/PlanScore/PlanScore/issues/94#issuecomment-356052283, we should **not** change the copy on the PLAN view to include live links to ELECTION views.

**Comment by gregallensworth** [comment]
This is coming together well. The UI is simple right-arrow and left-arrow cyclers. Performance is quite good.

https://planscore.org/north_carolina/#!1990-election-ushouse
https://planscore.org/north_carolina/#!2002-plan-ushouse

Still to do: Support for linking to a plan by an arbitrary year not necessarily that of the plan's starting year, e.g. `/north_carolina/#!2004-plan-ushouse` and `/north_carolina/#!2004-plan-ushouse` should **also** link to the 2002-2010 plan.

**Comment by danrademacher** [comment]
Due to confusion caused by the mocks in this issue I made on Friday, we accidentally modified this comment, https://github.com/PlanScore/PlanScore/commit/ff9b4096135cc26c3fd3498b68ad67ae8078d73a, to comment out the We have data sentence instead of the "Legislators drew" sentence. Greg will fix shortly.

**Comment by gregallensworth** [comment]
Sentence swapped again. Current screenshot of mobile UI:

![image](https://user-images.githubusercontent.com/3117633/34692807-3e0db190-f476-11e7-9299-e98660af67e3.png)

**Comment by danrademacher** [comment]
Reassigned to @tsinn for styling refinement

**Comment by gregallensworth** [comment]
Thrown back to me for a rewrite. To maximize clickable area for the two arrows, do the UI over again, overlaying the year so as to achieve hit boxes like this:

![image](https://user-images.githubusercontent.com/3117633/34696287-067e0010-f483-11e7-8472-0b64b2af85e6.png)

**Comment by gregallensworth** [comment]
279da5d -- The prev/next pick for mobile, has been refactored as described above. Text is positioned above a pair of 50/50 DIVs, so that fully half the screen width is clickable.
