### ISSUE TITLE
Don't stack Boundary pickers on mobile?

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#132]
During review with Mike yesterday, we were discussing that the hierarchy on mobile on the state page is challenging, because the meat of the scoring and content gets pushed so far down the page. I think we have some re-sorting to do there regardless, but one driver is this difference from design mock and build:

Xd:
![image](https://user-images.githubusercontent.com/1423200/34620487-7c0a7e02-f1fa-11e7-838b-ff0e820a86df.png)

Live build:
![image](https://user-images.githubusercontent.com/1423200/34620511-9109466c-f1fa-11e7-9fb9-dedf7789646e.png)

Design is iPhone 6 (375px). Not sure the text and hit areas will be big enough to get this look at 320, but it would help make the boundary picker less dominant.

Thoughts?

**Comment by tsinn** [comment]
I'm fine with this. 3 buttons across should work well.

**Comment by danrademacher** [comment]
Will need some CSS tweaking. I tried in the web inspector just making them 4-col and (a) had to make the text tiny to not wrap State Senate (maybe less padding?) and (B) they don't fall in line across the 12col. Maybe there's a `clear` in there somewhere?

![image](https://user-images.githubusercontent.com/1423200/34621108-b5b47e8a-f1fc-11e7-904f-b135487af22c.png)

**Comment by tsinn** [comment]
Working on now

**Comment by tsinn** [comment]
![image](https://user-images.githubusercontent.com/881970/34622383-05f030ec-f21b-11e7-82ef-bd2537f81b4a.png)

**Comment by tsinn** [comment]
![image](https://user-images.githubusercontent.com/881970/34622463-55547df0-f21b-11e7-863d-e945e84b729c.png)
