### ISSUE TITLE
Home map legend gets fuzzy as timeline changes

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#134]
Here's a weird one: As I select different years on the home page, the legend gets progressively more fuzzy (this is a GIF):
![z0bl2bfrth](https://user-images.githubusercontent.com/1423200/34635198-e1e1afd4-f240-11e7-91bc-cf89c60133d8.gif)

Maybe the legend title is redrawing on year year change and layering on top of itself?

Ah yes, many legends:
![image](https://user-images.githubusercontent.com/1423200/34635212-23bc96d0-f241-11e7-934c-34d9595f39e2.png)

**Comment by gregallensworth** [comment]
How odd. I can confirm what you see above: that multiple `legend` blocks are being added.

This may be a side effect of #114  in which the map-chart was reworked to no longer be destroyed and recreated, but merely have its data series replaced. As a result, the map DIV is no longer emptied and the legend can be put into place one time only at page start and not on data update.

On my displays I cannot confirm a visible fuzziness even after 40 year-clicks, so will confirm fix via debugger.
