### ISSUE TITLE
process state-level geography data

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#135]
Currently, US Congress data works and shows results, per #67. 

We have data for ~110 statehouse+plan combos, in this sheet, https://docs.google.com/spreadsheets/d/1qmm21sK_sCt-S31ug3OYPjmW_A1XgEg3jrKYlvaoUjE/edit#gid=1704544850

We need to:
- [x] pull down the files and name them consistently with UShouse data
- [x] do the geom simplification and compression into topojson
- [x] ~get tabular election results if possible~
- [x] make a generic style for maps without results data
- [x] load ~both CSV and~ topojson into the app

**Comment by danrademacher** [comment]
I downloaded all geometry here: 
/P_Projects/proj_p_s/Planscore/data/District_Geometries/statehouse

But also just a quick `wget -i statehousegeogs.txt` will do it locally for you if you save 
[statehousegeogs.txt](https://github.com/PlanScore/PlanScore/files/1640798/statehousegeogs.txt) into your desintation folder. And have `wget` installed on Windows.

**Comment by tsinn** [comment]
[topojson.zip](https://github.com/PlanScore/PlanScore/files/1643594/topojson.zip)
One thing to work through, maybe for Greg...
Different year files have different fields, `NAMELSAD00` and `NAMELSAD10` for example.
I therefore did not `-filter-fields` with the Mapshaper CLI.

**Comment by gregallensworth** [comment]
Attaching for reference:
* the script used to rename the JSON files to their expected `statehouse-PLAN.json` filenames
* the script which rewrites the *properties* for all geometries in all files, extracting from the relevant NAMELSAD field into a DISTRICT field



[fix_attribs.py.txt](https://github.com/PlanScore/PlanScore/files/1644182/fix_attribs.py.txt)
[rename_files.csv.txt](https://github.com/PlanScore/PlanScore/files/1644183/rename_files.csv.txt)
[rename_files.py.txt](https://github.com/PlanScore/PlanScore/files/1644184/rename_files.py.txt)



NOTE that I had to rename them with `.txt` extensions for Github to accept them. There are 2 `.py` files and ` .csv` file.

**Comment by gregallensworth** [comment]
Attaching for reference:

* the script used to rewrite the TopoJSON files' *properties* so as to have only the one **DISTRICT** field

[fix_attribs.py.txt](https://github.com/PlanScore/PlanScore/files/1644413/fix_attribs.py.txt)


This was significantly complicated, so the next data update will need to take care.

* Naming conventions are most often handled by the "Assembly District XX" or "State House District XX" conditions, but these are often non-numeric e.g. *27B* or *C-34* have been noted
* Massachusetts has a whole weirdness going on, combining numbers with counties (e.g. 7th Bristol) *but also* using spelled-out ordinals at times (e.g. Seventh Bristol in addition to 7th Bristol)
* The **SC5** plan adds the `HD-` prefix and leading 0s to the house district numbers (HD-007), unlike other SC plans and plans in other states

When the need comes up for a data update, I highly recommend visual examination of the district names to check for outliers.

* Capture the output as you run it: `python fix_attribs.py > review.txt`
* Then review the output file visually, confirming any district names which "seem weird" as at least being expected or consistent

**Comment by gregallensworth** [comment]
See also #177 and #178 which introduce the map behavior and some refinements to the data-switch behavior.

**Comment by gregallensworth** [comment]
Only to-do item here is to go through the states, and ensure that the polygons can show (yes, without election data / all nodata). Last time we ended up with 1 single plan (NC5 or NC5.1?) coming up with different scale/transform settings and so not being visible on the map.

**Comment by gregallensworth** [comment]
Checked over the TopoJSON files, and their transform numbers look A-OK.
