### ISSUE TITLE
Implement new mobile year picker on home page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#144]
Now that #129 has come together, that should become our year picker on narrow screens on mobile as well, replacing the current select menu.

**Comment by danrademacher** [comment]
Reassigned to @tsinn for styling refinement

**Comment by gregallensworth** [comment]
Thrown back to me for a rewrite. To maximize clickable area for the two arrows, do the UI over again, overlaying the year so as to achieve hit boxes like this:

![image](https://user-images.githubusercontent.com/3117633/34696284-002ecf3c-f483-11e7-906d-b3a1bbb27f39.png)

**Comment by gregallensworth** [comment]
279da5d -- The prev/next pick for mobile, has been refactored as described above. Text is positioned above a pair of 50/50 DIVs, so that fully half the screen width is clickable.

**Comment by danrademacher** [comment]
This is in place
