### ISSUE TITLE
Loading optimizations: Home page

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#147]
Since loading speed and total data payload are stronger considerations here than on most projects, when we get some breathing space let's analyze the payload and come up with ideas to streamline the loading.

Times below are with debugger simulating "Fast 3G"

In the case of state details, a condition was chosen to load a state map (polygon data) so as to achieve the "worst case" as far as data payload: map data, map tiles, etc.

Items tagged with a * are hosted within the site; items not so tagged are externally hosted.

#### Home page

https://planscore.org/index-new.html#!2016-ushouse

TOTAL: 490 KB    TIME: 4.5 seconds

Highcharts and JSON: 71 KB + 36 KB = 113 KB
CSV data: 68 KB   *
Site JS: 80 KB   *
jQuery + Bootstrap: 70 KB
The HTML: 50 KB   *
Google Analytics: 34 KB
Other JS libs: 28 KB
Images: 19 KB   *
Fonts: 15 KB
Site CSS: 12 KB   *

#### State Page with Map Data

https://planscore.org/south_carolina/#!2016-plan-ushouse-eg

TOTAL: 1023 KB    TIME: 5.5 seconds

CSV + TopoJSON: 315 KB   *
Map tiles: 260 KB
Site JS: 129 KB   *
Other JS libs: 115 KB
jQuery + Bootstrap: 70 KB
Highcharts: 71 KB
Google Analytics: 34 KB
The HTML: 32 KB   *
Images: 19 KB   *
Fonts: 15 KB
Site CSS: 12 KB   *

**Comment by gregallensworth** [comment]
1. I see no indication that Cloudfront is performing compression on the content, and much of the content would benefit hugely from on-the-fly gzip compression.

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront

CSV and JSON data in particular, are known to compress to 20% of their original volume, while CSS and JS files often see a 50% reduction in file volume. This reduced file size translates directly to improved loading experience.

**Comment by gregallensworth** [comment]
2. Alternative map tiles

On the state details page, map tiles account for about 13% of the total overhead. That is approximately doubled when Retina tiles are used, which by nature is mobile devices and potentially mobile data connections.

The divide is approximately 50/50 (146 vs 115) between the two tile layers: basemap & labels.

* Not loading a separate above-features labels layer would also shave off over 100 KB of payload.
* Other basemap tiles may look less pleasant, but also have a more compact file size.

(playing devil's advocate a bit here; worse-looking tiles and hidden labels are not great ux, but for payload optimization here are the numbers)

**Comment by migurski** [comment]
I’ve updated the Cloudfront configuration to “Compress Objects Automatically”. It might take a few minutes to propagate this change — can you retry your tests at ~2pm?

**Comment by gregallensworth** [comment]
3Highcharts on state page

On state details pages, Highcharts is used for one chart: the wasted votes. Highcharts accounts for 70 KB of payload on this page.

If the wasted votes chart were absent, or it were reformulated (something this simple could be done in pure CSS), then Highcharts could be omitted.

*Note that Highcharts is loaded on the front page as well; people visiting a state page having already visited the front page, would have Highcharts already in browser cache. Actual savings may be situation-dependent.*

**Comment by gregallensworth** [comment]
4. Increased simplification of TopoJSON content

State details pages: the `ushouse` TopoJSON files have a wide variation in file sizes, from 100 KB too 1000 KB, with many in the 200-300KB range.

Increased simplification on these would make for smaller file sizes, though may also round off some corners to make some very-gerry shapes less "weird looking".

**Comment by migurski** [comment]
What's an example of a TopoJSON file URL? AWS Cloudfront [uses Content-Type to determine what’s compressed](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#compressed-content-cloudfront-file-types), so these might already be gzipped if they’re coming back as `application/json`.

**Comment by gregallensworth** [comment]
Sample URLs of JSON and CSV content:
https://planscore.org/data/districtpolygons/ushouse-TX5.json
https://planscore.org/data/bias_ushouse.csv
https://planscore.org/data/elections_plans.csv

**Comment by migurski** [comment]
Thanks! Both of the content types represented here _should_ be compressed by Cloudfront. I’ll find out why they’re not.

**Comment by migurski** [comment]
Followup on this: after some unexplained delay, all of the expected content-types above are now correctly compressed.

**Comment by migurski** [comment]
I ran a selection of pages through a speed test to measure time-to-interactive, and the results are consistently under 5 seconds on 3G and DSL. The 1.8 second time for the home page on DSL is especially good:

- [Home page, DSL](https://www.webpagetest.org/result/180115_PM_addea4ee4e28acbfaa1d1ee0e9a06f77/): 1.8sec
- [Home page, 3G](https://www.webpagetest.org/result/180115_3R_e82175784741dc9872085c33038f727d/): 4.5sec
- [Plan page, DSL](https://www.webpagetest.org/result/180115_DE_1657cab1ca04aed3ec06d63fe1d2b2c7/): 4.5sec
- [Plan page, 3G](https://www.webpagetest.org/result/180115_DH_7c2cbfa61feb6a0a5c4c7dbf2c47a093/): 4.4sec
- [Upload page, DSL](https://www.webpagetest.org/result/180115_0G_32bb1c48d21894c3b529c82d7c2478a2/): 4.5sec
- [Upload page, 3G](https://www.webpagetest.org/result/180115_2R_07ebcf965fdb0fe4a5057dcdc97a4bc1/): 3.2sec

Great work on optimizing this for all kinds of users!
