### ISSUE TITLE
Map data doesn’t load when switching House levels

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#149]
![Image](https://i.imgur.com/YerXwre.jpg)

If I go to a state page for US Congress, then switch to State House, then back, the map is blank.

If I refresh, map data appears.

I assume we just need Boundary picker change to invoke map data load

**Comment by danrademacher** [comment]
I think I found the pattern. Here's a screencap movie:
https://drive.google.com/open?id=1HcN2gdrZXtUcYuhnwGeP2xnPajso8qmJ

Seems like I can make it happen on iOS consistently when switching Boundary on the state page. But then if I interact with the map, the data pops into place

**Comment by danrademacher** [comment]
Here's a second, more focused screencap:
https://drive.google.com/open?id=151y9r6UD1eaTMi-dIjM8lK7c3KgGdfbq

I confirmed that this does not happen on Safari desktop. Maybe it's just me?

**Comment by gregallensworth** [comment]
Instructions as in the video:
* Start on Texas, US House, 2004
* Scroll down and see the map
* Switch to state house
* Scroll down and see map vanished
* Switch back to US House
* Scroll down and see map visible, but with no drawings
