### ISSUE TITLE
Wording change suggestion

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#150]
On plan pages [such as Wisconsin’s](https://planscore.org/wisconsin/#!2012-plan-ushouse-eg), we use this EG langague:

> Republicans needed 9.9% fewer votes to win their 15 of 24 seats.

It might be confusing to someone who knows that there are 8 seats in Wisconsin and we’ve also lost the older “fair plan” language, so can we try new wording:

> Republicans needed to earn 9.9% fewer votes to win 15 of 24 races than under a fair plan.

**Comment by gregallensworth** [comment]
![image](https://user-images.githubusercontent.com/3117633/34783249-f5704536-f5df-11e7-841d-61a0e2f3af08.png)
