### ISSUE TITLE
Potential for adding data hints to Plan picker

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#161]
Greg shared the site with a friend who is "not a fan of maps" (these people exist!), and would like to see a timeline of bias change instead.

that could be a big change. Or it could be simple. A simple option would be a (more refined) version of this:

![image](https://user-images.githubusercontent.com/1423200/34892578-9df77cec-f78e-11e7-9a44-86de3244d73f.png)

Where the circle for each plan is colored by the direction of bias. this could either be all according to `eg_avg` but would have to switch by `house_level`. Or it could switch by both metric tab and house level.

We don't want to implement without reviewing with Mike.

**Comment by migurski** [comment]
I really like this idea, and would love to see a complete design pass fleshing it out.

**Comment by gregallensworth** [comment]
This is now in place.

![image](https://user-images.githubusercontent.com/3117633/35009910-0473c122-fab6-11e7-8a55-a0886fa03e1f.png)

**Comment by migurski** [comment]
It looks sharp.
