### ISSUE TITLE
Play function and button on home page?

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#163]
For a staff meeting, I manually made an animation of the home page map to march through time, like this:
![gz5eukbobh](https://user-images.githubusercontent.com/1423200/34892996-31dc1b60-f790-11e7-9f2e-a944f6cf025d.gif)

Given design and placement for a play/pause button, this wouldn't be too hard to implement and could be a cool feature that helps reveal the history in the data.

But it also complicates the page, so let's review with Mike before taking action.

**Comment by migurski** [comment]
I like this idea, generally. I think it might make sense to incorporate directly into the bubble timeline and feature prominently. It’s also a way to include a draggable playhead marking the currently-selected year, which is invisible in the current UI.

Here’s an ugly sketch:

![play-pause](https://user-images.githubusercontent.com/58730/34957352-1e299b70-f9e2-11e7-98f7-1dd3a2f2a769.png)

**Comment by danrademacher** [comment]
Tim's first pass design:

![image](https://user-images.githubusercontent.com/1423200/35002698-55f61aca-fa9f-11e7-8179-c9cafa866a34.png)

We're not quite sure yet how to implement this within the fully custom year picker, but Greg can probably find a way. 

Also need to consider how this would work on mobile. Maybe just hide it altogether since the forward-back experience is already pretty easy there?

**Comment by gregallensworth** [comment]
Phase 1: the selected year now has a label above it.   Styling is still pending feedback.

![2018-01-17 11_05_42-settings](https://user-images.githubusercontent.com/3117633/35061569-79d3ae9e-fb76-11e7-8832-ec6be17a6b69.png)
![2018-01-17 11_05_54-settings](https://user-images.githubusercontent.com/3117633/35061570-79fd34ee-fb76-11e7-9c3c-49f984110c54.png)
![2018-01-17 11_06_11-settings](https://user-images.githubusercontent.com/3117633/35061571-7a22f774-fb76-11e7-85a0-8714248a2d13.png)

**Comment by gregallensworth** [comment]
Phase 1 finally done. There was *a lot* of fussing to get pixel-perfect alignment of the marker lines to the little circles, at both circle sizes and on all display widths. But finally!

**Comment by gregallensworth** [comment]
Phase 2 is in place: an animation toggler. The screenshot below illustrates the button in "playing" mode.

![image](https://user-images.githubusercontent.com/3117633/35069315-a8c17a5c-fb8e-11e7-9f4a-23263c8934dc.png)

**Comment by gregallensworth** [comment]
Reopen: closure was accidental, need final signoff re colors and testing.

**Comment by migurski** [comment]
Looks good! Two thoughts: right now each frame of the animation takes about ~1.5sec, could it be half that? Also, each frame introduces a new history state in Safari and Chrome. Could it do that only when the animation is stopped at the end?

**Comment by gregallensworth** [comment]
26fa534 -- Timing changed from 1.5 seconds to 0.75 seconds.

**Comment by gregallensworth** [comment]
d22f0ae -- `#!` updating suppressed while animation is playing

Also, before this was applied, confirmed on all browsers (Android, Win, iOS, Mac) that the history states are replaced and not pushed. As such, Back button really did go back to prior page and never to prior year/boundary state.
