### ISSUE TITLE
Include more dynamic hint text with link in main well when there's no data

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#168]
Currently we show this:

![image](https://user-images.githubusercontent.com/1423200/35003760-a54b1e6a-faa2-11e7-848b-967730860ed4.png)

Ideally, we'd add a sentence at the end with a dynamic link to the nearest plan we do have or just the most recent. So something like:

"The closest we have to year you asked for is [YYYY]()."

But not sure if we can reliably determine a logical "closest". Just nearest by value?

If that's not feasible, then:

"The most recent data we have is for  [YYYY]()."

**Comment by gregallensworth** [comment]
The logic is in place, and works as follows:
* Favor the minimum "delta" between the selected year and a year for which we have data.
* In event of a tie (typically 2 years before + 2 years after) favor the higher-numbered more-recent year.

Example:
* `/alabama/#!2016-plan-statehouse-eg` picks 2010 as that is the closest
* `/alabama/#!2009-plan-statehouse-eg` picks 2010 as it is the closest (not how 2009 isn't even a valid choice, but is handled properly)
* `http://local.planscore.info:8000/alabama/#!1992-plan-statehouse-eg`  picks 1994 as 1990 and 1994 are a tie, but 1994 is more recent



Screenshots:

![image](https://user-images.githubusercontent.com/3117633/35016092-09042068-facc-11e7-8484-c1c52d412bb3.png)

**Comment by danrademacher** [comment]
Great! and yet another typo from me, darn it.

We need "the" inserted before "year" in this sentence:

>"The closest we have to the year you asked for is YYYY."
