### ISSUE TITLE
Revise function of home page bead bar to include available span of years, pick most recent

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#169]
Right now, the homepage picker shows a blank map on the state house when I go from 2016 US House to 2016 State house.

This is technically correct, but user experience is that the map is "broken."

Ideally, in the case where someone hasn't changed the year picker and swaps boundaries, they'd fall back to 2014, with the labeling for current year in place as shown in #163.

But if we ALWAYS fall back to the Max() for a given boundary, then even if you choose 1982 or something, switching boundaries would jump you to 2014 for State House or 2016 for US House. Not ideal.

Not sure what the best solution is here that avoids downstream problems while also addressing the narrow problem of people thinking map is broken when they load State House without changing anything else. 

Thoughts?

**Comment by gregallensworth** [comment]
Done.

* Calling `selectBoundaryType()` invokes a new feature I put in, `fudgeYearIfNoData` 
* If `fudgeYearIfNoData` is specified and a pre-examination finds 0 data rows for that year, then the next closest year is chosen.
  * Closest year that has data, and the higher-0numbered more-recent year in event that two years are equally "far" from the chosen year.

Year selection does not do this. If one switches from US House to State House in 2016, it switcdhes over to State House 2014. If one then picks 2016, they get no data as one would expect.
