### ISSUE TITLE
Changes to "Balanced" plans on state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#170]
A couple of changes to Balanced plans:

- [x] If the Plan is showing as 0%, remove the "+" before it:
> +0% Balanced

should be

> 0% Balanced

- [x] For plans above or below 0 but still balanced, keep all as is in number and color, but replace "Balanced" inside the gray box with the party valence. Keep sentence about balance to the right as is.

**+1% Democrat** This metric indicates a balanced plan.
**+1% Republican** This metric indicates a balanced plan.

**Comment by gregallensworth** [comment]
Done. Screenshots of various outcomes:


![2018-01-16 12_46_27-start](https://user-images.githubusercontent.com/3117633/35011548-60ddb274-fabb-11e7-8201-be45651cd601.png)
![2018-01-16 12_46_42-planscore __ north carolina](https://user-images.githubusercontent.com/3117633/35011549-6100519e-fabb-11e7-89b3-420b61df25b4.png)
![2018-01-16 12_46_58-planscore __ north carolina](https://user-images.githubusercontent.com/3117633/35011550-61251c90-fabb-11e7-96c2-b0efa91cbded.png)

**Comment by gregallensworth** [comment]
**NOTE** that the words in the issue description were to use negative numbers for Republican bias, e.g. *-12% Republican*

Previous peripheral discussions were that these numbers should be absolute values, so as not to convey a "Republicans are negative" sort of notion. (and then to invite further questions why the negative numbers are on the right side of an axis?)

At this time the old absolute-value behavior is used. Let me know if this is to change, explicitly stating negative numbers for Republicans.

**Comment by danrademacher** [comment]
You read my mind correctly! The negative on R value was an error
