### ISSUE TITLE
Plan Picker Election Years bug when clicking from State House to US House

### ISSUE THREAD

**Issue by tsinn** [PlanScore/PlanScore#172]
![image](https://user-images.githubusercontent.com/881970/35024411-4a656b5c-fb0d-11e7-82c1-473245f8d7d5.png)

**Comment by gregallensworth** [comment]
Interesting! I thought I saw this one once, but it fixed itself when I reloaded and I thought it was just some video glitch. Confirmed, and I know the fix...

Fixed in 0c37780
