### ISSUE TITLE
Review Plan Picker colors

### ISSUE THREAD

**Issue by tsinn** [PlanScore/PlanScore#173]
For instance, the fill for 2016 in this screen shot should be most saturated red
![image](https://user-images.githubusercontent.com/881970/35047263-6142ed04-fb67-11e7-9bfe-2d6bd7f97a5b.png)

**Comment by gregallensworth** [comment]
See also: this is a continuation of #161 and #167

**Comment by gregallensworth** [comment]
Fixed in eedd445
