### ISSUE TITLE
Bellcurve overset on 3 col page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#174]
![image](https://user-images.githubusercontent.com/1423200/35063841-1fb1a13a-fb7d-11e7-8025-d40bed1276b1.png)

https://precog.mapzen.com/PlanScore/PlanScore/fc5c9d1/plan.html?enacted-NC5.1

@tsinn I wonder if this can be handled with additional breakpoints or other simple CSS?

**Comment by migurski** [comment]
Fewer breakpoints would be fine, too.

**Comment by danrademacher** [comment]
Sure. simpler = better! But I know the challenge with this has been that we need to make it absolute size to get everything to line up reliably, vs just 100% of the container, which we tried at first but had trouble making sure the plumbline landed in the precise right spot
