### ISSUE TITLE
Pale gray state labels for nulls on front page map

### ISSUE THREAD

**Issue by tsinn** [PlanScore/PlanScore#179]

**Comment by tsinn** [comment]
Apply to small state rectangles, too

**Comment by gregallensworth** [comment]
5456744 implements a hack to the Highcharts `formatter` to apply a CSS style to the `text` elements for nodata. This creates the alternatively-colored labels as requested.

However, this creates a new issue that these states now exist, and thus are subject to mouseover effects and clicking. Therefore `selectState()` to bring up a popup, must gracefully handle a nodata condition.

**Comment by gregallensworth** [comment]
This is now in place: nodata states have labels, and therefore have a "we have no data" handling when their popup is displayed.

NOTE that this conflicts with a previous request, that nodata states not be interactive things on the map. Highmaps cannot do that however: mouse events must be turned on/off globally.

**Comment by danrademacher** [comment]
I wonder if a more feasible improvement of this solution would be to hide the "Learn More>" link from the state popup div if we have no data. that way at least we're not asking people to "Learn More" on a page that can't tell them anything

**Comment by danrademacher** [comment]
@migurski when you have a chance can you take a look at this solution on live site and let us know what you think? Thread above shows the constraints we're working in -- mostly, no known way in HighCharts to have state label appear and **not** be clickable. My hope is that now that the selected state popover is non-blocking of UI _and_ no longer includes Learn More> link, this is a reasonable middle ground.

**Comment by migurski** [comment]
This solution works well for me! I’m noticing something frustrating about the popover, and unsure if it’s new. It can only be closed by clicking the `x`, and not by the two things I tried: clicking the same state again or hitting the escape key.

**Comment by gregallensworth** [comment]
The new ways to close a popover would be good usability gains. I'll close this issue (regarding labels) and open a new one (regarding this new popover behavior and another one I've noticed).
