### ISSUE TITLE
Front page, map: make labels not touch borders

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#180]
![image](https://user-images.githubusercontent.com/3117633/35127056-1989d71c-fc65-11e7-8950-341b62370b93.png)

Highcharts doesn't have any sort of countermeasures on letting the labels (at centroids?) touch borders. In some cases this is really goofy looking.

It will be significantly tedious work, but should be possible, to put in some sort of pixel-fussing code that finds the labels in the DOM, then applies a few px of additional fussing. This may not work on all displays, but should at least improve the collisions on more displays...

**Comment by danrademacher** [comment]
Looks like an unintended side effect of this is that the labels fuss _every time_ the year changes. Need to fuss only on pageload.

Watch the labels march along:
![7pfcsgg6we](https://user-images.githubusercontent.com/1423200/35131326-58446480-fc7a-11e7-9a78-d2c7e64e5078.gif)

**Comment by gregallensworth** [comment]
Big goof on my part. @tsinn had previously discovered an undocumented feature of the GeoJSON file used by Highmaps. The features contain a `hc-middle-x` and `hc-middle-y` property, which is used to fine-tune label placement. This would be the preferred mechanism.

e31db74 removes my pixel-fussing code.

e31db74 also renames the map's JSON file to something more clearly obvious: `usmapchart.json` This more obvious filename is also mentioned in comments. This will help the maintainers in 2024 to find the appropriate file a tad more easily.

**Comment by gregallensworth** [comment]
GeoJSON file has been updated with improved label placements.
