### ISSUE TITLE
Sidebar doesn’t clear out when no data exists

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#181]
Steps to reproduce:

1. Visit https://planscore.org/connecticut/#!2012-plan-statehouse-eg 
2. Click “US House”

The sidebar timeline remains visible but not clickable. It should have an empty state.

**Comment by danrademacher** [comment]
Good catch. Looks like we have an empty state, but only invoked if you explicitly refresh browser after hash change:
![image](https://user-images.githubusercontent.com/1423200/35129580-200fc400-fc71-11e7-8f93-f6e188647365.png)

So we should invoke that on hash change not just page load.

**Comment by gregallensworth** [comment]
This is now in place, properly hiding the sidebar content when there are no data.


![2018-01-18 17_09_48-planscore __ connecticut](https://user-images.githubusercontent.com/3117633/35129868-8ba33912-fc72-11e7-92f1-a9ceafb29710.png)
![2018-01-18 17_09_57-planscore __ connecticut](https://user-images.githubusercontent.com/3117633/35129869-8bd8dec8-fc72-11e7-904d-a9c0dca91a99.png)
