### ISSUE TITLE
CSS for links -- add an underline

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#194]
Underline link text on most of the site; I’m not sure the colored links are enough to make it clear what’s a link and I’m doing things like adding connections to the new Historical Data page.

**Comment by migurski** [comment]
This may need a quick visual pass; I noticed that the zoom buttons on the maps have underlines, which shouldn't happen:

<img width="398" alt="screen shot 2018-02-12 at 3 05 07 pm" src="https://user-images.githubusercontent.com/58730/36124772-40334ac4-1006-11e8-98b2-29a7e741d462.png">

**Comment by tsinn** [comment]
*should* be all set to merge my branch with `static-site`

**Comment by migurski** [comment]
Should there be a PR for this somewhere?

**Comment by danrademacher** [comment]
For the record, this was resolved and merged in https://github.com/PlanScore/PlanScore/pull/222
