### ISSUE TITLE
Review vertical space above and below tab block

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#195]
Add vertical margin to page elements like the Tab Block, so they’re separated similarly to paragraphs and headers. The metrics block on the home in particular looks a bit smashed up against the preceding paragraph.

**Comment by tsinn** [comment]
added padding
```
ul.nav.nav-tabs {
    border-bottom: 1px solid #b3b3b3;
    padding-top: 15px;
}
```
