### ISSUE TITLE
Fix Wisconsin zeros for 2012-2016

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#198]
Instances of "This plan is more skewed than 0% of the enacted plans we have analyzed nationwide." on this page: https://planscore.org/wisconsin/#!2012-plan-statehouse-eg

**Comment by migurski** [comment]
Also some wrong-looking 50’s on this page: https://planscore.org/wisconsin/#!2002-plan-statehouse-eg

**Comment by danrademacher** [comment]
This was an issue with the input data in Google Sheets where on PERCENTRANK columns on STATEHOUSE only, the range within we were calcing PERCENTRANK was wrongly set as a relative ref and shrank by one row in each row of data, so by the bottom of the list, we were ranking among almost 0 items. This has been fixed for all PERCENTRANKs in `bias_statehouse.csv` and verified as already correct in `bias_ushouse.csv`

**Comment by danrademacher** [comment]
Now looking better!

![image](https://user-images.githubusercontent.com/1423200/35823727-58bda14e-0a65-11e8-8536-89f5bb0b7737.png)
