### ISSUE TITLE
Modify metric texts and cutoffs

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#200]
Currently, the metric cutoff for a balanced plan is ±4%. Mean-Median has a slightly different range from the other two metrics, so it should instead be ±2%.

We should also keep the complete metric sentence even when a plan is balanced. For example, [this Minnesota page](https://planscore.org/minnesota/#!2002-plan-ushouse-eg) should still have the “balanced plan” text, but it should also have the other sentence “Votes for Republican candidates were wasted at a rate 4% lower than votes for Democratic candidates.”

**Comment by gregallensworth** [comment]
- [ ] change the structure of `BIAS_BALANCED_THRESHOLD`, and modify `lookupBias()`, so as to look up the score *for a specific metric* At this time this usage of `BIAS_BALANCED_THRESHOLD` is the only diff

- [ ] Modify "This metric indicates a balanced plan." wordings (all 3) to **also** include the "how skewed it is" text, e.g. "This metric indicates a balanced plan. The median Republican vote share was 2.9% higher than the mean Republican vote share."
  * NOTE that this means that having the is-balanced text to the right of the button, will no longer happen. Is-balanced text will now be longer than any of the how-unbalanced texts, which already goes onto the next line. OK by me, but pointing it out as a predicted visual change. See 'shots below.

<img width="615" alt="balanced-short text on right" src="https://user-images.githubusercontent.com/3117633/35868917-be24fd04-0b12-11e8-91d6-531da7d7452f.png">
<img width="591" alt="imbalanced-text_on_next_line" src="https://user-images.githubusercontent.com/3117633/35868919-be77cfd4-0b12-11e8-8f8e-833520d636b5.png">

**Comment by gregallensworth** [comment]
The above set of commits brings the requested changes to the is-imbalanced flag being separated from the favored party, and of BIAS_BALANCED_THRESHOLD being metric-specific.

It **also** brings a refactoring of the metric-boxes logic here. There are some new details in the `lookupBias()` return, such as
* the `cssclass` so we don't need to to "party.toLowerCase() if unbalanced else 'balanced'" sort of logic
* the D/R boxes on the page now use the `favor_party_code` instead of replicating the "favor party.substr(1).toUpperCase()" logic

**Comment by gregallensworth** [comment]
<img width="590" alt="imbalanced" src="https://user-images.githubusercontent.com/3117633/35871517-5115fb58-0b19-11e8-9863-45c7513a47d1.png">
<img width="593" alt="isbalanced" src="https://user-images.githubusercontent.com/3117633/35871518-512a76dc-0b19-11e8-854c-583e9ad2a9fa.png">

**Comment by gregallensworth** [comment]
If this looks good to you, go ahead and close this Issue. If not, let me know.

**Comment by migurski** [comment]
Looks great!
