### ISSUE TITLE
New chart for partisan bias

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#201]
Split off from #197, since we have all needed data for this one.

Here's a mockup:
![image](https://user-images.githubusercontent.com/1423200/35873067-81a31cde-0b1d-11e8-835e-1861c4d5542f.png)

And the math:

To make the bars, each party starts at 50, then we take the `bias_avg` and do the following pseudocode:

```
abs(bias_avg)/2 = seatshare_variance
if bias_avg < 0 then (r_seatshare = 50+seatshare_variance) and (d_seatshare = 50-seatshare_variance)
if bias_avg > 0 then (r_seatshare = 50-seatshare_variance) and (d_seatshare = 50+seatshare_variance)
```

Not for reference -- this includes slight wording variations from the pencil sketch in #197, since it seems clearer to emphasize that the PB chart is about **seat share** and not vote share.

**Comment by danrademacher** [comment]
Hmm, couple things here:

1. in NC, we show more seats to Dem than R, but should be reverse:
![image](https://user-images.githubusercontent.com/1423200/35896015-fc79b066-0b6e-11e8-9131-816f2741f0ca.png)
Note that [Maryland](https://planscore.org/maryland/#!2016-plan-ushouse-pb) is properly showing as biased D, so doesn't seem to be a simple reversal. 

2. turns out the example chart I had from experts wrongly showed that we do PB/2. The whole bias should be added to the winning party and subtracted from the losing party.

So NC would be 23% D and 77% R

**Comment by gregallensworth** [comment]
Done.

Now, after correction and coming live presently, it reads as follows:

```
  // pb_score is defined as the bias_avg field in the case of Plans
  // and the bias field in the case of Elections

    let r_seatshare = 50;
    let d_seatshare = 50;

    if (pb_score > 0) {  // as usual, R is >0
        r_seatshare += pb_score;
        d_seatshare -= pb_score;
    }
    else if (pb_score < 0) {
        r_seatshare -= pb_score;
        d_seatshare += pb_score;
    }
```

**Comment by gregallensworth** [comment]
And new output, coming live shortly:

![image](https://user-images.githubusercontent.com/3117633/35928607-696c6fce-0be2-11e8-8f9a-f6af964289e1.png)

**Comment by danrademacher** [comment]
Right on for NC, but something wrong in Maryland:
https://planscore.org/maryland/#!2016-plan-ushouse-pb

![image](https://user-images.githubusercontent.com/1423200/35932300-33652902-0bec-11e8-886f-4b45b8175f1a.png)

this should be showing reverse with bias to D.

**Comment by gregallensworth** [comment]
Latest fix for the math. I think the + and - values to the D/R sides... should be the *absolute value* of thre bias value, and not the bias value.

* If the value was <0 to indicate a +R skew, it would *subtract -25*
* if the value is >0 to indicate a +D skew, it would *add 25*

This commit fixes that, by using the absolute value.
