### ISSUE TITLE
Possibly-incorrect sentence for Vermont

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#203]
Here: https://planscore.org/vermont/#!2014-plan-statehouse-eg

The sentence says “We used three metrics to analyze this plan. The metrics do not consistently indicate a skew in either party’s favor,” but the three metrics all point D. Possible bug?

**Comment by gregallensworth** [comment]
I see it: a casualty of the recent wording change:
```
const metrics_favor_d = [ favor_party_eg, favor_party_pb, favor_party_mm ].filter((party) => { return party == 'Democrat'; }).length;
```

These days it's "Democratic" and not "Democrat"

Later code uses the **partycode** attribute which would be a *d* or *r* and thus acts more like a constant.

**Comment by gregallensworth** [comment]
This commit reworks the "2-out-of-3 tallies " logic here:
* The *partycode* is used, which is less likely to change than the wording
* The *isbiased* delta is now taken into account, now that (as of #200) we give back a bias party even if the bias is below threshold

**Comment by migurski** [comment]
Thank you! Switching from human-language to a less-changey code sounds like a great approach.
