### ISSUE TITLE
Adjust histogram colors and map colors

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#212]
A few changes related to histograms and colors that could be batched together:

- Currently [the front-page state house map](https://planscore.org/index-new.html#!2012-statehouse) looks a bit paler than [the U.S. house map](https://planscore.org/index-new.html#!2012-ushouse). Can we change the color spectrum to be Congress-specific and state house-specific? The worst state house plans should looks as bright red/blue as the worst congressional plans. 
- The [state-house histograms](https://planscore.org/north_carolina/#!2012-plan-statehouse-eg) also look a bit paler than the [U.S. house histograms](https://planscore.org/north_carolina/#!2012-plan-ushouse-eg) when they’re at similar positions in the distribution.
- The state house scores have a narrower distribution overall, so their ranges should also be narrower.  For example, both the [congressional](https://planscore.org/north_carolina/#!2012-plan-ushouse-eg) and [state house histograms](https://planscore.org/north_carolina/#!2012-plan-statehouse-eg) for the efficiency gap go from 22%D to 22%R, even though we never see state house EGs that big.

**Comment by danrademacher** [comment]
Looking back at the source charts for these, I did set them all with a single `max` and `min` on the X axes, with the idea that color values would therefore be comparable across house levels, but sounds like that's actually not desirable and we should have `max` and `min` specific to each level. 

I can regenerate the charts for State House, and make anew for State Senate. 

To get a sense of difference, here are the `min` and `max` for State House:
* EG: +/- 17% (US House is +/- 22%)
* PB: +/- 25% (US House is +/- 30%)
* MMD: +/- 10% (US House is +/-11%)

**Comment by gregallensworth** [comment]
Code changes:

- [ ] **constants.js** defines `BELLCURVE_SPREAD` as a structure, so the appropriate one may be chosen *per metric*  This needs to be changed to vary by both metric & districttype
- [ ] **functions.js** defines `drawBiasBellChart()` which is the only consumer of the `BELLCURVE_SPREAD` constant  This will need updating as described above.

**Comment by gregallensworth** [comment]
Boundary type is already supplied to `drawBiasBellChart()` as the `boundtype` parameter. As such, function signatures will not change and callers do not need alteration.

**Comment by gregallensworth** [comment]
Code changes have been made per above, into a new branch. The last item will be to adjust **constants.js** to contain the min/max values for all 9 boundary-and-metric combinations. (or at least the 6 for *ushouse* and *statehouse* since *statesenate* is a no-go at this time)

- [ ] statehouse eg; currently 0.22
- [ ] statehouse pb; currently 0.30
- [ ] statehouse mm; currently 0.11
- [ ] ushouse eg; currently 0.22
- [ ] ushouse pb; currently 0.30
- [ ] ushouse mm; currently 0.11

**Comment by danrademacher** [comment]
Updated curves:
[updated_statehouse_curves.zip](https://github.com/PlanScore/PlanScore/files/1721895/updated_statehouse_curves.zip)

And new min/max:
- [ ] statehouse eg; new 0.17
- [ ] statehouse pb; new 0.25
- [ ] statehouse mm; new 0.10

**Comment by gregallensworth** [comment]
There is a new PR for this, based off the `gda-212-histogramrefactor` branch.

Pull it for local testing, or check out the screenshots in this issue. Let me know of more changes, or else go ahead and merge the PR and close this issue.
