### ISSUE TITLE
Show percentile values regardless of skew level

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#213]
In the “How Does This Plan Compare” areas of a balanced plan, can we still include the skew percentile language? For example, [this balanced plan](https://planscore.org/north_carolina/#!1998-plan-ushouse-eg) would still say “This plan is more skewed than `x`% of the enacted plans we have analyzed nationwide” even though `x` is very small.

**Comment by gregallensworth** [comment]
<img width="557" alt="2018-02-13 13_18_53-planscore __ north carolina" src="https://user-images.githubusercontent.com/3117633/36174226-8749d5b2-10c0-11e8-9750-36a025772e69.png">
<img width="553" alt="2018-02-13 13_19_09-planscore __ north carolina" src="https://user-images.githubusercontent.com/3117633/36174227-876c0fd8-10c0-11e8-9ca0-3b327ce136d4.png">
<img width="565" alt="2018-02-13 13_19_18-planscore __ north carolina" src="https://user-images.githubusercontent.com/3117633/36174228-878b5398-10c0-11e8-9462-ba9dbd3fdca7.png">



@migurski  See above for screenshots of the new behavior.

For plans which are imbalanced, the only difference is that the phrase "No consistent skew was found in favor of either party." will be omitted. It would be possible to instead put in "This metric indicates a bias towards PARTYNAME" but that's kind of covered immediately above in larger font.

If you like it, head over to the attached PR and merge it in at your convenience.
