### ISSUE TITLE
Refactor of color-scaling operations: front map, lookupBias(), state navs

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#215]
Broken off from #212 which conflated changes to the front-page choropleth with changes to the state-page bellcharts. Though both red and blue, the math and back-end code are separate. (but perhaps not for long?)

Request: Make the front-page choropleth sensitive to district boundary type, The current fixed value of `BIAS_SPREAD_SCALING = 0.25` is not great for all spreads. *No need to make it sensitive to metriic as well, as the front-page choro always uses the EG metric.*

Front-page choropleth is based on the `BIAS_SPREAD_SCALING` constant, which is one single constant (`0.25`) to map the value onto the color gradient. it would be more consistent to use the **color** item from `lookupBias()` output, so all things are using the same color ramp calculator

- [x] `lookupBias()` accepts a metric param but not a boundtype param, and would need adjustment

- [x] `lookupBias()` should use `BELLCURVE_SPREAD` as this is now our go-to for the 9-combination set of scaling constants

- [x] all callers to `lookupBias()` will need adjustment to supply that new parameter: index, states, maybe others?
  - [x] front-page choropleth
  - [x] front-page state listing
  - [x] state page yearpicker nav
  - [x] check for other uses of `lookupBias().color`

- [x] front page choropleth could use `BELLCURVE_SPREAD` interpolation instead of `BIAS_SPREAD_SCALING`

**Comment by gregallensworth** [comment]
All of the above are done, and the front-page map now uses boundtype-sensitive color ramping.

*NOTE* that this still does not ever give a condition in which as State House is as vivid as the US House, as the distributions simply are not the same.

```
NC statehouse 0.129 score / 0.17 max = 0.758
NC ushouse    0.203 score / 0.22 max = 0.922
```

And this case, FL 2012 being the most-extreme State House biasing score:
```
FL 2012:  .137 / .17 = 0.8
```

State House EG scores max out at 80% of the absolute value of their range, while US House EG scores max out at 90% and higher. As such, the extreme State House simply are not as extreme as the extreme US House.

* Option 1: Ignore it. The math is right, the distributions just don't go as extreme.

* Option 2: Manually adjust the max value for State House from `0.17` to a lower value such as `0.14` so the range used is more narrow and thus these extremes will be amplified.

**Comment by danrademacher** [comment]
This is fundamentally connected to #217 -- the extremity here is _correct_ from the data, which means all the colors are and curves are scaled correctly. However, current UI is unable to display that extreme

**Comment by gregallensworth** [comment]
We went with option 2, to change `BELLCURVE_SPREAD.statehouse.eg` from 0.17 to 0.15, to bring out the extremes in State House data.

- [x] Update **constants.js**
- [ ] new chart SVG `statehouse_eg_plan_curve.svg` based on new min/max of 0.15 (relevant to #212 which had these replaced a bit ago)

**Comment by danrademacher** [comment]
New chart based on +/-0.15
[statehouse_eg_plan_curve.svg.zip](https://github.com/PlanScore/PlanScore/files/1722255/statehouse_eg_plan_curve.svg.zip)

**Comment by gregallensworth** [comment]
There is a new PR for this, based off the `gda-212-histogramrefactor` branch.

Pull it for local testing, or check out the screenshots in this issue. Let me know of more changes, or else go ahead and merge the PR and close this issue.
