### ISSUE TITLE
Implement State Senate Data, curves, geometry

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#216]
- [x] Data to be dropped as CSV from here: https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=317626967
- [x] State Senate curve for EG:
[statesenate_eg_plan_curve.svg.zip](https://github.com/PlanScore/PlanScore/files/1722016/statesenate_eg_plan_curve.svg.zip). +/- is 22% for X axis labels.
- [x] Geometry URLs pulled from https://docs.google.com/spreadsheets/d/1qmm21sK_sCt-S31ug3OYPjmW_A1XgEg3jrKYlvaoUjE/edit#gid=1704544850&range=H:H
  - [x] display of State Senate district polygons
  - [x] display of voter details (if available)
- [x] see also 226 regarding the lack of metrics data here; only EG has metric data, and the metric tabs will need work to handle missing data
- [x] See also #112 in which the State Senate buttons are disabled and would need to be re-enabled

**Comment by gregallensworth** [comment]
Commit 6742eba adds **bias_statesenate.csv** 

Front page map & listing are confirmed to work with the data as-given. *Many years have no data at all* but the ones which do, display as expected.

My working branch `gda-216_112-statesenate` includes the changes in `gda-217-oddyears` and `gda-223-statepage-betternodata` Therefore the front page map is properly fudging VA's 2003 and 2011 data as 2004 & 2012.

**Comment by gregallensworth** [comment]
State Senate district polygon datasets have been added,

Examples of them working:
http://local.planscore.info:8000/virginia/#!2011-plan-statesenate-eg
http://local.planscore.info:8000/virginia/#!2003-plan-statesenate-eg
http://local.planscore.info:8000/michigan/#!2014-plan-statesenate-pb
http://local.planscore.info:8000/oregon/#!2012-plan-statesenate-eg
http://local.planscore.info:8000/oregon/#!2002-plan-statesenate-eg
http://local.planscore.info:8000/north_carolina/#!2012-plan-statesenate-eg
http://local.planscore.info:8000/north_carolina/#!2004-plan-statesenate-eg

Example of nodata condition (map hidden):
http://local.planscore.info:8000/north_carolina/#!2002-plan-statesenate-eg
