### ISSUE TITLE
State pages: handling of lacking metric data

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#226]
It is not the case that all state&year&district combinations, have data for all 3 scores. This is particularly the case with State Senate data per #216 which is known to have only EG scored and not MM and PB, but is also "a general thing to handle"

- [x] The state page metric tabs, need to be adjusted to handle a condition where a metric score is lacking. At this time, spec is simply a "we didn't calculate this" message as the tab content

- [x] confirm final wording for the "we didn't calculate this" message as the tab content

- [x] The words "We used three metrics to analyze this plan." may now be untrue if we have only 1 or 2. (State Senate is known to have EG only, 1 metric and not 3)

- [x] The 2/3 criteria for "All plans agree that this is biased..." needs rethinking, for the case of 2 metrics or 1 metric *and final tweaks to wording*

- [ ] confirm final "bias summary" wording for the various conditions: 1/1 or 0/1, 1/2, etc.

**Comment by gregallensworth** [comment]
Commit e9bbf09 on the `gda-216_112-statesenate` branch. The top of state pages, now has wording better tuned to the number of metrics which are being used.


#### Wording Used

With all 3 metrics available:
* We used three metrics to analyze this plan. All three metrics indicate a pro-Democrat skew.
* We used three metrics to analyze this plan. All three metrics indicate a pro-Republican skew.
* We used three metrics to analyze this plan. Two of the three metrics indicate a pro-Democrat skew.
* We used three metrics to analyze this plan. Two of the three metrics indicate a pro-Republican skew.
* We used three metrics to analyze this plan. The metrics do not consistently indicate a skew in either party’s favor.

With 2 metrics available:
* We used two metrics to analyze this plan. Both metrics indicate a pro-Democrat skew.
* We used two metrics to analyze this plan. Both metrics indicate a pro-Republican skew.
* We used two metrics to analyze this plan. The metrics do not consistently indicate a skew in either party’s favor.

With 1 metric available:
* We used one metric to analyze this plan. This one metric indicates a pro-Democrat skew.
* We used one metric to analyze this plan. This one metric indicates a pro-Republican skew.
* We used one metric to analyze this plan. This one metric does not indicate a skew in either party's favor.

#### Screenshots

<img width="558" alt="2018-02-15 12_56_25-planscore __ oregon" src="https://user-images.githubusercontent.com/3117633/36280630-bcefeeaa-124f-11e8-8838-706ad795cdb9.png">
<img width="569" alt="2018-02-15 12_56_42-planscore __ oregon" src="https://user-images.githubusercontent.com/3117633/36280631-bd0f79be-124f-11e8-954d-e15df5198e29.png">
<img width="598" alt="2018-02-15 12_56_53-planscore __ oregon" src="https://user-images.githubusercontent.com/3117633/36280632-bd309658-124f-11e8-9005-4745733e1f66.png">

**Comment by gregallensworth** [comment]
The metric tabs, now have their content suppressed when that metric is undefined (actually `NaN`)

Screenshots:

<img width="551" alt="2018-02-15 13_21_52-planscore __ virginia" src="https://user-images.githubusercontent.com/3117633/36281668-4884d90a-1253-11e8-95e8-a8a875275c19.png">
<img width="588" alt="2018-02-15 13_22_02-planscore __ virginia" src="https://user-images.githubusercontent.com/3117633/36281670-48aac110-1253-11e8-9ef7-eafa53718553.png">
![Uploading 2018-02-15 13_22_13-PlanScore __ North Carolina.png…]()

**Comment by danrademacher** [comment]
I just pulled ’gda-2016_112-statesenate` and running locally, I don’t see the missing metric sentence showing here:

![image](https://user-images.githubusercontent.com/1423200/36282975-ca0724fc-1257-11e8-97a2-db35e72d4b29.png)
http://0.0.0.0:8000/virginia/#!2003-plan-statesenate-pb

or here:
![image](https://user-images.githubusercontent.com/1423200/36282991-dbbb0cea-1257-11e8-8954-e4bf15d53a55.png)
http://0.0.0.0:8000/virginia/#!2003-plan-statesenate-mm

I assume [this new code](https://github.com/PlanScore/PlanScore/commit/ea2946e076a9a33ae31ea952f609c3054d54a70c#diff-3979de8ca6c5818f3e57197850bb8fedR691) (which I confirmed is present for me locally) should be preventing these views. 

Maybe nulls are being read as zeros in some cases?

**Comment by gregallensworth** [comment]
cdb28d6 -- The last of the HTML changes to support this. I hadn't pushed these yet.

**Comment by danrademacher** [comment]
And confirmed, working locally. Let's bundle this up in a PR for @migurski and then he can review copy as part of that and update if needed. In the PR comments, maybe highlight the lines that would need to change if he wants it to read differently?

If he wants something more different, also fine to kick it back to us, but if language is good or close, then he can tweak and merge.

**Comment by gregallensworth** [comment]
The "we didn't calculate this" wording, per MM:

How about an active sentence that uses all the words, e.g. “We did not calculate Partisan Bias for California’s 2012 Redistricting Plan” ? Regular, non-bold type is probably fine.
