### ISSUE TITLE
Share capability / URL shortener

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#231]
TBD capability to Share pages, either by getting a shortened URL to copy-and-paste, or else with direct links to FB & Twitter to share the posting. Some possibilities...

#### Twitter share button

Pretty straightforward: https://dev.twitter.com/web/tweet-button

In other applications, these do work well for dynamically rewriting their `text` parameter to e.g. include URL params currently in effect.

*This does mean some tight coupling between the hash-updating code (or a hashchanged event) and rewriting the tweet button's params.*

#### Facebook share button

Pretty straightforward: https://developers.facebook.com/docs/plugins/share-button

In other applications, this has proven amenable to having its `data-href` parameter modified to suit URL params currently in effect.

*This does mean some tight coupling between the hash-updating code (or a hashchanged event) and rewriting the share button's params.*

#### Lightbox & URL shortener

The other case we often have, is that one simply wants the hyperlink to paste into some other application such as email or a spreadsheet. The most basic approach is of course the address bar itself. Beyond that, we usually go with an URL-shortening mechanism such as Google URL Shortener API, and present the shortened URL in a lightbox-style modal UI.

While the T and FB buttons have well-known UIs and a very small visual footprint, this mechanism tends to require more custom behavior to present the URL in a usable fashion.

**Comment by danrademacher** [comment]
Iceboxing this until we hear more demand for it
