### ISSUE TITLE
Analyze home>state page user flow

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#236]
Based on Google Analytics to date, it appears we have fewer people getting from home page to specific state pages than we would expect, given user tests where nearly all subjects said first thing they would do is clock their state.

A few options:
1. Make homepage state click immediate link to state page
2. Make the Lean More link in the popover into a big button
3. Wire in a new GA events on home to understand what people are doing there.

I'm going to make separate issues for 1 and 3 and bookmark 2 as something we might return to.

**Comment by migurski** [comment]
According to GA, we’re seeing a higher percentage of people choosing Pennsylvania from the homepage during the past three days than the previous three. 10% of total visits went from `/` to `/pennsylvania/` since Feb 21, compared to 2% from Feb 18 to Feb 20. This is an encouraging sign.
