### ISSUE TITLE
Add custom GA events on home page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#237]
Looks like we wired in lots of custom events on state pages, but based on my review of current  GA stats and code, looks like we didn't add any events to home page. 

Related to #236, we're trying to understand better why relatively few users are visiting state pages form home page.

So let's add these events on home:
- [x] Choose any year
- [x] Clicked any state
- [x] Switched Geog level
- [x] Switched tabs on the bottom

For years and states, I think we want those to be general for all interactions of that type, vs. specific year and states, so we can quickly see if folks are interacting with the map. 

If it is simple to add which years or states they choose in another event/GA element I'm not thinking of, that's gravy.

**Comment by gregallensworth** [comment]
The `selectYear()` et al are higher-level functions which are called at time which would not be appropriate for logging, e.g. `selectYear()` is called when the timeline animation plays, so would result in a series of false events as the years are iterated. Either bind directly to clicks on both mobile and desktop yearpickers, or else create new options allowing the animations not to trigger GA event logging.

`selectState()` may be going away or be significantly reworked per issue #238 so be wary of changes there.

- [ ] state click
- [ ] yearpicker click (desktop)
- [ ] yearpicker click (mobile)
- [ ] Boundary type clicks
- [ ] Metrics tabs change

**Comment by gregallensworth** [comment]
### Round one: Years, States, Boundaries

#### Boundary type changes
```
ea:frontpage-boundarytype
ec:ushouse
```
```
ea:frontpage-boundarytype
ec:statehouse
```


#### State details selected
```
ec:Missouri
ea:frontpage-selectstate
```

Per issue 238 the visible behavior may change to simply forwarding to the state page, which would result in a `statedetails` action also being logged when that page loads.


#### Year changed
```
ec:1992
ea:frontpage-yearselected
```

These are specifically NOT logged when one plays the timeline as an animation.

These ARE specifically logged when the mobile yearpicker is used, and one is constrained for prev/next behaviors. This may have implications as to the interpretation of "popular years" based on their presence in the logs, as one may need to cycle through several years to get to the one intended.
