### ISSUE TITLE
Odd "marching forward no data" behavior in Virginia

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#241]
Splitting off from #223 because it seems like a separate issue. As Mike described, there's a somewhat odd behavior on VA page where you can never get State House and Us House to show data at the same time, seemingly even when plans inclusively cover similar years.

Starting at `/virginia/#!1998-plan-ushouse-eg` Here's an animation of the experience:
![rmrdee9fxl](https://user-images.githubusercontent.com/1423200/36550421-1d02a13e-17aa-11e8-88e2-360b04e2a3d7.gif)

It seems odd that (a) we can never see plans with a single click even though they cover overlapping years and (b) the "nearest" year marches forward even just by clicking nearest, which seems more like it should be a symmetrical relationship -- A nearest B, B nearest A.

But I think (A) is actually the more important problem and goes all the way back to the State Page having been originally built based on picking an _election_ and then the plan is selected as an artifact of that. So in fact we never have data for the same exact YEARS in VA between even-number congressional elections and odd-number state house.

However, since the whole experience is based on _plans_ now, a reasonable expectation is that a click from the [1998-2000 Congress plan](https://planscore.org/virginia/#!1998-plan-ushouse-eg) in VA to State would then land you inside the [1991-1999 state plan](https://planscore.org/virginia/#!1991-plan-statehouse-eg)

**Comment by gregallensworth** [comment]
From Dan:

"It seems odd that (a) we can never see plans with a single click even though they cover overlapping years ... goes all the way back to the State Page having been originally built based on picking an election"

That's right: the snapping behavior is only on page landing, not on later changes of UI, and that behavior was described in #223 and #224   This was intentional, to not take too many liberties once a person was intentionally changing UI selections... and also to support compatibility with Election views, which we know will be reinstated some day.

So, looks like we're changing expectations:
* When UI changes, *do* perform the `fudgeYearIfNoData` hack on subsequent action *so long as we are in Plan mode*

**Comment by gregallensworth** [comment]
`updateStatsFromCsvContent()` rewritten to support two different behaviors.

### Election mode

* The exact year given is used. If not found, a nodata condition exists.
* In nodata condition, a suggestion is given as to the closest year.

Note that this will still have a ladder-stepping effect, as years must be an exact match. If no election was in 1992 then either 1991 or 1993 must be offered; and when there is no row for 1993 then either 1992 or 1994 must be offered.

If folks are finding this suggest-a-year behavior confusing under such conditions, maybe it's not doing them any favors and we should just suggest that they use the yearpickers?

### Plan Mode

Plan mode will no longer do year-fudging, but will display whatever data are the best fit for the year selected. The definition of "best" is open to interpretation, so current behavior is as follows:

*http://local.planscore.info:8000/virginia/#!1987-plan-ushouse-eg*
* Falls clearly within the 1982-1990 plan
* That plan is shown

*http://local.planscore.info:8000/virginia/#!1997-plan-ushouse-eg*
* This year falls *in between* the 1994-1996 plan and 1998-2000 plan, not clearly within a plan
* 1994-1996 is chosen
* Logic being, that in 1997 this is the most recent plan not yet superseded; should a new plan not have been enacted in 1998 this plan would still have been in effect

*http://local.planscore.info:8000/virginia/#!2040-plan-ushouse-eg*
* Falls after the latest year for which we have data
* Most recent plan is shown

*http://local.planscore.info:8000/virginia/#!1900-plan-ushouse-eg*
* Falls before the first year for which we have data
* Oldest plan is shown
