### ISSUE TITLE
Alaska zoom is off kilter

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#244]
https://planscore.org/alaska/#!1992-plan-statehouse-eg

Loads like this:
![image](https://user-images.githubusercontent.com/1423200/36621931-74d8cec8-18af-11e8-82ab-995022a8c51b.png)

Should look like this:
![image](https://user-images.githubusercontent.com/1423200/36621925-64f07092-18af-11e8-8772-0c7be1a1bdd7.png)

I assume it's an issue on this line?
https://github.com/PlanScore/PlanScore/blob/static-site/_common/constants.js#L140

Date line problem?

**Comment by gregallensworth** [comment]
Yeah. That pesky date line.

Fortunately I didn't use an automated item such as `stuff.getBounds()` but a set of constants for the states' bbox. As such, a simple edit to `STATE_BOUNDING_BOXES` should suffice.
