### ISSUE TITLE
Enable state senate data

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#258]
We have 111 unique shapefiles that should include State Senate boundaries that we need to prep for adding state senate geometries to the site.

https://docs.google.com/spreadsheets/d/1qmm21sK_sCt-S31ug3OYPjmW_A1XgEg3jrKYlvaoUjE/edit#gid=1704544850

As I recall, @tsinn did the other polygon prep using command-line MapShaper.

**Comment by tsinn** [comment]
[state_senate.zip](https://github.com/PlanScore/PlanScore/files/2120311/state_senate.zip)

Steps:
1. Batch reproject in QGIS
2. Remove most fields (retain 2)
`mapshaper P:\proj_p_s\PlanScore\Data\state_senate\*.shp -filter-fields SLDUIDFP00,NAMELSAD00 -o P:\proj_p_s\PlanScore\Data\state_senate\fields\ format=shapefile`
3. Rename fields
`mapshaper P:\proj_p_s\PlanScore\Data\state_senate\fields\*.shp -filter-fields GEOID=SLDUIDFP00,DISTRICT=NAMELSAD00 -o P:\proj_p_s\PlanScore\Data\state_senate\fields\rename\ format=shapefile`
4. Convert to topojson and simplify, retaining 10% of removable vertices
`mapshaper P:\proj_p_s\PlanScore\Data\state_senate\fields\rename\ -simplify 10% -o P:\proj_p_s\PlanScore\Data\state_senate\fields\rename\simplify\ format=topojson`

**Comment by tsinn** [comment]
@gregallensworth, can you review the attached state senate districts and confirm these will work for the web maps?

**Comment by danrademacher** [comment]
hmm, one thing I see straight away is we'll have to rename these to the schema used for the other shapes:
`statehouse-AK4.json`
`ushouse-TX1.1.json`

We have those plan names in the source sheet, https://docs.google.com/spreadsheets/d/1qmm21sK_sCt-S31ug3OYPjmW_A1XgEg3jrKYlvaoUjE/edit#gid=1704544850&range=G:G, but we'd need to crosswalk from existing SHP names and doe `statesenate-[plancode].json`

**Comment by tsinn** [comment]
[state_senate.zip](https://github.com/PlanScore/PlanScore/files/2120515/state_senate.zip)
Renamed and re-uploaded...

**Comment by danrademacher** [comment]
I should have tagged this issue in https://github.com/PlanScore/PlanScore/commit/45bd7cf727fa7a95af6f5e60213d1038187ee5f7

**Comment by danrademacher** [comment]
We're holding off on finishing this and deploying until we get further word from Mike and PlanScore team. Note that the data for State Senate lacks Mean Median Bias and Partisan Bias. I am checking with them whether we'll get that data or have to make changes to gray out and disable those tabs when those metrics are not present.

**Comment by gregallensworth** [comment]
Relevant to "Need bellcurve backgrounds for all 3 metrics." item above:

While debugging #281 I see that **/images/statesenate_eg_plan_curve.svg** now exists, but the other two do not:

```
GET /images/statesenate_bias_plan_curve.svg 404 Not Found
GET /images/statesenate_mmd_plan_curve.svg 404 Not Found
```

**Comment by danrademacher** [comment]
Ah, thanks for catching that -- I had them but forgot that I had to force them:
```
nothing to commit, working tree clean
danrademacher@MacBook-Pro PlanScore % git add WEBSITE_OUTPUT/images/statesenate_*
The following paths are ignored by one of your .gitignore files:
WEBSITE_OUTPUT
hint: Use -f if you really want to add them.
hint: Turn this message off by running
hint: "git config advice.addIgnoredFile false"
danrademacher@MacBook-Pro PlanScore % git add -f WEBSITE_OUTPUT/images/statesenate_*
```

Added those in this commit:
https://github.com/PlanScore/PlanScore/commit/fd09bdc000e900c762f16511b8705ab0c5fbe294
