### ISSUE TITLE
Update with 2018 election data

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#280]
Working from here:
https://docs.google.com/spreadsheets/d/1aBffpd3Fv0tCvz6waMk2fGhyV3ZfSSUaWyJKrzi-HL8/edit#gid=2042561440

Data updates needed:
- [x] new `ushouse_production.csv`
- [x] new `statehouse_production.csv`
- [x] new `statesenate_production.csv` — **NEW**

Image updates:

Plan-level curves that need updates:
- [x] statehouse_bias_plan_curve.svg
- [x] statehouse_eg_plan_curve.svg
- [x] statehouse_mmd_plan_curve.svg
- [x] ushouse_bias_plan_curve.svg
- [x] ushouse_eg_plan_curve.svg
- [x] ushouse_mmd_plan_curve.svg
- [x] statesenate_bias_plan_curve.svg — **NEW**
- [x] statesenate_eg_plan_curve.svg — **NEW**
- [x] statesenate_mmd_plan_curve.svg — **NEW**

Election-level curve can be ignored:
- statehouse_bias_election_curve.svg
- statehouse_eg_election_curve.svg
- statehouse_mmd_election_curve.svg
- ushouse_bias_election_curve.svg
- ushouse_eg_election_curve.svg
- ushouse_mmd_election_curve.svg

**Comment by danrademacher** [comment]
Notes:

* Refer to this tab for the new production example for US House: https://docs.google.com/spreadsheets/d/1aBffpd3Fv0tCvz6waMk2fGhyV3ZfSSUaWyJKrzi-HL8/edit#gid=1367628396

In the old data, we had a line for every election, but much of the data was repeating since it was actually for the plan:

state | year | code | plan | eg_adj_avg | eg_avg_percentrank | eg_adj | eg_percentrank | bias_avg | bias_avg_percentrank
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
AL | 1972 | AL1972 | AL1 | -0.052 | 0.515 | -0.058 | 0.47 | 0.044 | 0.46
AL | 1974 | AL1974 | AL1 | -0.052 | 0.515 | 0.070 | 0.554 | 0.044 | 0.46
AL | 1976 | AL1976 | AL1 | -0.052 | 0.515 | -0.119 | 0.824 | 0.044 | 0.46
AL | 1978 | AL1978 | AL1 | -0.052 | 0.515 | -0.080 | 0.624 | 0.044 | 0.46
AL | 1980 | AL1980 | AL1 | -0.052 | 0.515 | -0.075 | 0.581 | 0.044 | 0.46

In the new data, it looks like we have a single line for each **plan** and then a new min and max field to say when this applied:

min code:2020 | max code:2020 | count code:2020 | plan:2020 | avg eg_adj:2020 | avg bias:2020 | avg mmd:2020 | sum wasted_dem:2020 | sum wasted_rep:2020 | sum votes_dem:2020 | sum votes_twop:2020 | sum seats:2020 | sum seats_dem:2020 | sum seats_r:2020 | percentrank eg_adj:2020 | percentrank bias:2020 | percentrank mmd:2020
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
AL1972 | AL1980 | 5 | AL1 | -0.074 | 0.071 | 0.091 | 1,277,068 | 774,933 | 2,350,939 | 4,104,001 | 35 | 20 | 15 | 0.688 | 0.594 | 0.993
AL1982 | AL1990 | 5 | AL2 | -0.033 | 0.131 | 0.068 | 1,451,168 | 1,263,014 | 3,379,744 | 5,428,365 | 35 | 25 | 10 | 0.377 | 0.870 | 0.812
AL1992 | AL2000 | 5 | AL3 | -0.050 | -0.058 | -0.002 | 1,918,372 | 1,408,262 | 3,186,482 | 6,653,267 | 35 | 14 | 21 | 0.507 | 0.514 | 0.051

So we'd need to refactor a bit to not simply grab the row from the relevant election but instead to I think first filter by state (give me all rows for AL) and then compare the selected years to the ins and maxes to find the correct row. Not complex, but different from what we have.

**Comment by danrademacher** [comment]
Looking deeper at this, I see that we do have a couple of parts of the state page that explicitly rely on counting elections data from the source sheet:
![image](https://user-images.githubusercontent.com/1423200/96539261-83547a00-124f-11eb-9153-0fd35f8151a8.png)

Based on code comments, I see we found in the past that the only way to really know what elections to list on the left side was to pull from the CSV, and also that we left machinery in place to someday show election level data in addition to plan level data, though we stripped out plan-level data. Not sure if if election-level data might still be a someday potential. See comments here:
https://github.com/PlanScore/PlanScore/blob/static-site/_statetemplate/state_template.js6#L191-L195

@migurski, based on my findings in this comment, I suspect the best course is to retain the same format for the tabular data where each row is an election with a State, Year, Plan, but with mostly plan-level data, instead of each row as a plan with a min/max. I imagine there's a way to do this with a modified query statement, but not quite sure yet of the best way.

**Comment by danrademacher** [comment]
This version of the US House should work for what the front end is expecting:
https://docs.google.com/spreadsheets/d/1aBffpd3Fv0tCvz6waMk2fGhyV3ZfSSUaWyJKrzi-HL8/edit#gid=30765872

Pulls together election level data from "US House pre-prod. 2020" and "US House prod. 2020" into "US House ELECTION prod. 2020" If this approach is acceptable, should be pretty easy to replicate for the other two levels.

**Comment by migurski** [comment]
This approach makes sense to me; I tried an alternate method but it was equivalent to the US House you prototyped, so I jiggle some names and otherwise left it alone.

**Comment by danrademacher** [comment]
OK, starting to come together in https://github.com/PlanScore/PlanScore/tree/static-site-2020dataupdate

We have Senate and 2018 on the home page!
![fOknRm7h2M](https://user-images.githubusercontent.com/1423200/96829983-766e8c80-13ef-11eb-91f4-1a725cd5dfa1.gif)

Noticing some interesting nationwide gaps in state senate data -- 2011-12, 2001-02, 1991-92, 1981-2. So consistently at the beginning of each decade, we have no data. I checked back at the source in gSheets, and that's true in the source there as well. We'll assume that's expected and proceed.

**Comment by migurski** [comment]
Those gaps are odd! I’ll check upstream, see if we have any explanation.

**Comment by danrademacher** [comment]
Curve images update in process -- but seeing more change than I expected on the ones we already had:
![image](https://user-images.githubusercontent.com/1423200/96958648-f14cab80-14b2-11eb-9947-c2cb011ac1a1.png)

Gradient fills are the pre-2018 data. Blue lines are the new curves as exported from the [2020 data sheet](https://docs.google.com/spreadsheets/d/1aBffpd3Fv0tCvz6waMk2fGhyV3ZfSSUaWyJKrzi-HL8/edit#gid=344536830). 

Makes me wonder if something is off in the source charts -- or worse was off with our original charts. These new ones use the same method of taking min and max from the data, dividing into 16 bins, then assigning plans to those bins. 

I rediscovered and confirmed in [this old issue comment](https://github.com/PlanScore/PlanScore/issues/97#issuecomment-354208050) that we have to flip the histograms after export, so D is left and R is right. 

Still, since we have only one new election, I'd expect tiny changes in this charts. @migurski anything you know about in the data update that would make plan distribution change quite a bit? Maybe we have more historical elections feeding in here too?

If it's expected that the curved changed a fair amount, we can rapidly get these styled, exported, and deployed.

**Comment by migurski** [comment]
The gaps are expected for State Senate: we didn't calculate senate scores for the first elections under plans, due to concerns about staggered seats.

I’m comfortable with these charts; we did a scatter plot check of the new vs. old data and saw differences within expected bounds. The methodology is slightly different between the prior data and this data, and we have new coverage that may be accounting the changes you’re seeing here. 

Let’s move forward!

**Comment by danrademacher** [comment]
This is all complete and now in this branch https://github.com/PlanScore/PlanScore/tree/gda-216_112-statesenate along with fix for #281. Pending answer on #282, we can file a PR and this is ready to deploy
