### ISSUE TITLE
Curve graphics "get stuck" on State Senate

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#281]
Working in this branch: https://github.com/PlanScore/PlanScore/tree/gda-216_112-statesenate, we have nearly complete updated data and curve SVGs with State Senate enabled.

But there's something amiss with the loading of State Senate curves -- they load as expected, but then never change from there when I select US House or State House. Switching between US House and State House works as expected.

Here's a GIF showing what's happening: http://g.recordit.co/82L6j9VwDz.gif

**Comment by gregallensworth** [comment]
Got it: a single-character typo: `statesentate`   Therefore it was not removing the `statesenate` CSS class, and it is the CSS classes which determine the background image to be used.  I have corrected this, still in the **gda-216_112-statesenate** branch.

**Comment by danrademacher** [comment]
Confirmed fix locally. Pending #282 for deploy
