### ISSUE TITLE
Retain NC special case table?

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#282]
In our work on #281 and #280, @gregallensworth noticed a special case in the NC state page in this commit:
https://github.com/PlanScore/PlanScore/commit/f231df92486cda805d2f72850876d35b4199f304

Still live here: https://planscore.org/north_carolina/#!2016-plan-ushouse-eg (edited) 

![image](https://user-images.githubusercontent.com/1423200/97229143-2566eb80-1795-11eb-85de-b7f9c06fcf41.png)

since we're adding 2018 data across the whole site, can we remove that static table? Or should we retain it?

**Comment by migurski** [comment]
Let’s remove it, thanks for checking!
