### ISSUE TITLE
Research Scott Jehl’s new table for plan pages

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#361]
https://codepen.io/scottjehl/pen/abJrPOP?editors=1100

@paulirish what do you think?

**Comment by paulirish** [comment]
Oh man, he did it! I was messing with the new position:sticky on thead functionality recently, but failed. This is aces. 

Yeah I'll put a PR for this.

**Comment by migurski** [comment]
Sweet. It looks really perfect for our use of tables, especially if it can make them look good on mobile. They’ll need some attention in combination with @spncr’s work on the CLC visual design changes, per this before/after comparison:

* http://planscore.org/plan.html?20210602T011219.957012722Z
* https://dev.planscore.org/plan.html?20210602T011319.378415404Z

**Comment by paulirish** [comment]
> They’ll need some attention in combination with @spncr’s work on the CLC visual design changes, per this before/after comparison:
> 
> * http://planscore.org/plan.html?20210602T011219.957012722Z
> * [dev.planscore.org/plan.html?20210602T011319.378415404Z](https://dev.planscore.org/plan.html?20210602T011319.378415404Z)

Ah yeah.... The tables look pretty funky now. The new Avenir typeface increases the textwrapping in the headings.  

@migurski is now a good time to start smoothing out any issues due to the new styles on dev?

**Comment by migurski** [comment]
Now is a great time, as long as we keep @spncr and team informed!
