### ISSUE TITLE
Upgrade the upload flow

### ISSUE THREAD

**Issue by paulirish** [PlanScore/PlanScore#365]
Through the upload flow I see a few opportunities for a cleaner UX.

## upload page
* The text list of current supported states is BIG. (Also.. wow.. it's come a long way in the past couple months!) I could see it moving to a small caption below the SVG graphic.
* The filetypes chunk relates to the "Upload a district plan as a geospatial file containing Polygon or MultiPolygon shapes" sentence. Could reorder that a bit.
* having two buttons really throws me. at the very least I'd want the Score button to be disabled prior to a file being selected.  But I'd prefer having just a "Select a file to upload" button, where the upload begins immediately after filepicker selection.

## annotate stage
* I'd love to avoid asking the user to refresh. We could poll every ~3 seconds.

## scoring & plan
* Same bit about refresh. This part definitely takes longer (it took ~60s on my recent uploads). We could poll every 5s and provide more detail about progress. For example:

> ✅ Plan file uploaded
> ✅ Plan annotated
> ✅ Starting analysis
> ✅ Reading district geometries
> 🔄 Iterating slice subtotals: 0 / 44

And at completion, this progress UI would just disappear instantly in exchange for the plan content. Or, we could be slightly more gentle and provide a "Analysis complete" message, pause for a couple seconds, and then replace things with the plan.  

----

Thoughts?

**Comment by migurski** [comment]
I agree with basically everything suggested here. The scoring stage can be quite fast, or for some large plans up to a full few minutes. We can introduce a progress array in the upload JSON instead of relying on latest message text which might be a forward-compatible way to introduce this.

**Comment by paulirish** [comment]
> We can introduce a progress array in the upload JSON

Yeah I saw the `progress` field in the current payload already gives us the slice subtotal array (i think?)

![image](https://user-images.githubusercontent.com/39191/123690447-3cb91580-d809-11eb-8d24-7dcc1bd90ba6.png)

So, I probably already have all the data I need on the f/e.

**Comment by migurski** [comment]
Also, here are all the possible observed messages to date:

    "Can't score this plan: {state name} is not a currently supported state"
    "Can't score this plan: TopologyException: {error}"
    "Can't score this plan: something went wrong, giving up."
    "Finished scoring this plan."
    "Found {n} districts in the {model} plan with {n} seats."
    "Giving up on this plan after it took too long, sorry."
    "Reading this newly-uploaded plan. Reload this page to see the result."
    "Scoring this newly-uploaded plan. {n}% complete. Reload this page to see the result."
    "Scoring this newly-uploaded plan. Adding up votes. Reload this page to see the result."
    "Scoring this newly-uploaded plan. Reload this page to see the result."

**Comment by migurski** [comment]
After merging https://github.com/PlanScore/PlanScore/pull/376 I occasionally see the error message “Didn't connect to PlanScore API server.” I think this might be confusing for a user though I like the one-button improvement we’ve got now. How can we accommodate a slow server response so a user gets a more helpful message?

**Comment by paulirish** [comment]
> After merging #376 I occasionally see the error message “Didn't connect to PlanScore API server.” I think this might be confusing for a user though I like the one-button improvement we’ve got now. How can we accommodate a slow server response so a user gets a more helpful message?

Cool, thanks for letting me know.

I was seeing the GET to /upload take about 1s, so expected this error to happen if someone chose a file in <1s, but.. yeah if you're running into it, then it's not good enough. 

I'll build in a little extra time for the /upload GET to finish
