### ISSUE TITLE
Tweak header?

### ISSUE THREAD

**Issue by paulirish** [PlanScore/PlanScore#366]
Small irk of mine on the plan page... The metadata at the top of the plan page looks so similar to the static text I didn't immediately discern which was which.

Proposing some small style tweaks to distinguish a bit easier:

![image](https://user-images.githubusercontent.com/39191/123530427-e8018780-d6ae-11eb-9e3e-58d1e8d032cd.png)

**Comment by migurski** [comment]
This is a big improvement.
