### ISSUE TITLE
Fix fonts in Firefox browser

### ISSUE THREAD

**Issue by migurski** [PlanScore/PlanScore#391]
Header fonts don’t appear on plan pages: https://planscore.org/plan.html?20210421T190939.675034041Z

**Comment by paulirish** [comment]
Same in Chrome.

> Access to font at 'https://planscore.campaignlegal.org/fonts/362FC8_2_0.ttf' from origin 'https://planscore.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I ran into this in development as well.. I set this header: 

    "Access-Control-Allow-Origin": "*"

It needs to be set on the webfont requests, but I can't think of a reason to not set it on all requests.  This'll have to be set on the `planscore.campaignlegal.org` serving side.

**Comment by migurski** [comment]
This might be an easy change.

**Comment by migurski** [comment]
Wrestled with this a little then tried invalidating the CDN cache and it seems to work. Closing for now…
