### ISSUE TITLE
Initial tests: "python3 setup.py test" 2 errors

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#49]
My test machine's OS is Ubuntu 16,

Running through the setup docs `python3 setup.py test` is giving me 2 errors.

```
ERROR: test_lambda_handler (planscore.tests.test_score.TestScore)
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/tests/test_score.py", line 243, in test_lambda_handler
    'key': 'uploads/sample-plan/upload/file.geojson'}, None)
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/score.py", line 193, in lambda_handler
    new_districts.append(json.load(object['Body']))
TypeError: the JSON object must be str, not 'bytes'

ERROR: test_load_tile_precincts (planscore.tests.test_districts.TestDistricts)
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/tests/test_districts.py", line 450, in test_load_tile_precincts
    precincts1 = districts.load_tile_precincts(storage, '12/2047/2047')
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/districts.py", line 258, in load_tile_precincts
    geojson = json.load(object['Body'])
TypeError: the JSON object must be str, not 'bytes'
```

**Comment by migurski** [comment]
Thanks Greg! What version of Python do you have installed? (`python3 --version`) I’ve been building and testing with 3.6 for the most part.

**Comment by gregallensworth** [comment]
Python is `3.5.2`

I hope to get another look at this today, get some more useful diagnostics.

**Comment by gregallensworth** [comment]
Test for `load_tile_precincts`

`json.load()` is choking on the response body, expecting a string and instead getting a Bytes object.

This is true, per the code below:

```
    if object.get('ContentEncoding') == 'gzip':
        object['Body'] = io.BytesIO(gzip.decompress(object['Body'].read()))
```

Solution:

Have both gzip and non-gzip conditions return a proper string, and then use `json.loads()` instead of `json.load()`

```
    if object.get('ContentEncoding') == 'gzip':
        object['Body'] = gzip.decompress(object['Body'].read()).decode()
    else:
        object['Body'] = object['Body'].read()
```

**Comment by gregallensworth** [comment]
f9279ab brings a patch to `district.py` and `score.py` to decode the gzip output into a `str` and not a `BytesIO`, so `json.loads()` can handle both conditions.

Grepping the rest of the files, I see one more spot where this issue is likely to recur, which does not appear in the unit tests. `score.py  score_district()  line 77`

**Comment by gregallensworth** [comment]
2d3feee brings a patch to `score.py score_district()`

* Similar to fixes above, renders body to string... but here a *byte* string

* New function `util.temporary_bytes_file()` to write a byte string to disk and give back filename, parallel to `temporary_buffer_file()` which operates on a buffer.

**Comment by migurski** [comment]
Thanks Greg; it’s interesting that this only showed up as a test failure on your system. Did Python’s JSON support introduce less stringent bytes handling in 3.6?

**Comment by migurski** [comment]
Ah, yes:

> Changed in version 3.6: s can now be of type bytes or bytearray. The input encoding should be UTF-8, UTF-16 or UTF-32.

https://docs.python.org/3/library/json.html#json.loads
