### ISSUE TITLE
Unable to run debug-site.py, syntax error FIELD_NAMES

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#55]
Trying to run `make clean localstack-env && ./debug-site.py` per instructions.

```
Traceback (most recent call last):
  File "./debug-site.py", line 2, in <module>
    import planscore.website
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/website/__init__.py", line 2, in <module>
    from .. import data, score, constants
  File "/home/planscore/virtualenv_planscore/PlanScore/planscore/score.py", line 24
    FIELD_NAMES += tuple([f'REP{sim:03d}' for sim in range(1000)])
```

I see that the lines read as follows:
```
# Fields for simulated election vote totals
FIELD_NAMES += tuple([f'REP{sim:03d}' for sim in range(1000)])
FIELD_NAMES += tuple([f'DEM{sim:03d}' for sim in range(1000)])
```

These seem to be missing the `.format(sim=sim)` ?

**Comment by gregallensworth** [comment]
This is the (relatively) new f-strings feature of **Python 3.6**, while Python 3.5 is the 3.x that comes with Ubuntu. I'll see about updating instructions to accommodate.

**Comment by gregallensworth** [comment]
PR 56 brings the documentation improvements clarifying that Python 3.6 is required, thus working around this "error"

**Comment by migurski** [comment]
Thanks Greg!
