### ISSUE TITLE
Content: Footer links

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#57]
Sitewide footer was not addressed in functional mockups, so the one being implemented is a fairly generic footer with the GIN credits, and "Link Here?" sorts of links. What is the vision for the sitewide footer?

**Comment by danrademacher** [comment]
### Basic content

[icon] Email: info@planscore.org
[icon] [@PlanScore](https://twitter.com/PlanScore)
[icon] [Github](https://github.com/PlanScore/PlanScore)

PlanScore is a fiscally sponsored project of [logo] [GreenInfo Network](http//:greeninfo.org)

### Other things we might include

@migurski I see there's a PlanScore Medium publication (https://medium.com/planscore), but it has no stories. Should we assume that will be live by launch?

**Comment by danrademacher** [comment]
We just need SVG replacement logos here to they’re sharp on retina

**Comment by gregallensworth** [comment]
Noting that the new footer SVGs look great, and therefore there should be no need for the PNG versions anymore.

```
WEBSITE_OUTPUT/images/twitter-logo.png
WEBSITE_OUTPUT/images/email-logo.png
WEBSITE_OUTPUT/images/github-logo.png
WEBSITE_OUTPUT/images/greeninfo.png
```

**Comment by migurski** [comment]
The footer might need to get slightly taller as well; I just added an Olark contact form and it wants the bottom slice of screen real estate for itself, configurable for the left or the right:

<img width="1280" alt="screen shot 2018-01-09 at 11 57 26 pm" src="https://user-images.githubusercontent.com/58730/34761500-f4b637fa-f598-11e7-89a8-5e81b62d1e4b.png">

Adding more bottom padding for the footer or choosing one side for the links would avoid a conflict.

**Comment by danrademacher** [comment]
Since @tsinn's change was to HTML and not CSS, it doesn't propagate to @migurski's pages, but is present here: https://planscore.org/patternlibrary_htmltemplate/index.html.

**Comment by migurski** [comment]
I’ll update my end!

**Comment by danrademacher** [comment]
@migurski regarding Olark and the footer. Seems like we should also add the contents of `olark-embed.html` to our sitewide header so it's avaialable everywhere on the static site. Does that seem right?

**Comment by migurski** [comment]
I put it exclusively on the scoring and upload pages, because I figured that’s where people might be having problems. I'm slightly reluctant to have it everywhere, just to limit potential inbound stuff to the places where someone’s trying to get a job done.

**Comment by danrademacher** [comment]
OK, makes sense. I suspect the historical data pages will lead to questions too, like "Why is Texas so blue?" but better if folks Tweet that sort of stuff toward @PlanScore and turn it into a public convo vs a private user-feedback response chore.

**Comment by migurski** [comment]
I like that idea!
