### ISSUE TITLE
Content: Header and PlanScore logo + Page Title

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#58]
Depicted in the functional mockups is a top navbar:
* PlanScore logo
* Score a Plan
* What is PlanScore?

- [x] final PlanScore logo for integration into sitewide header
- [x] actual list of links *and also* open a new Issue for each of those pages so we can track it as a task
- [x] other design details such as font, color, background color/image, ...
- [x] the H1 title present on home page and presumably on every page:: size, color, font

**Comment by danrademacher** [comment]
Looking good. We'll open specific issues if other items come up
