### ISSUE TITLE
Content: front page text, paragraphs & three tabs

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#59]
Need final copy for this section, the few paragraphs describing what gerrymandering is, as well as the tab content describing the three metrics. Existing content is placeholder from functional mockups.

Also, the styling fore this narrative content was not defined in the functional mockups.

- [x] Title & text for "What is gerrymandering?" and "How do we measure it" sections
- [ ] styling for those narrative paragraphs
- [ ] styling for those headings
- [ ] Text for metric: *Efficiency Gap*
- [ ] Text for metric: *Mean/Median*
- [ ] Text for metric: *Partisan Bias*
- [x] styling for the tab nav
- [x] styling for the 3 tab content: font & size & color

**Comment by danrademacher** [comment]
gDoc for the tab copy:
https://docs.google.com/document/d/1iIjfLkfixZ6JZPDziAbFd9W4br2fXa87qJHZzFgqvOE/edit#

**Comment by danrademacher** [comment]
Finalized in PR #137
