### ISSUE TITLE
Front page: popup when a state is selected

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#63]
Per #61 a State picker exists on the front page, as a surrogate for clicking/tapping a state should the click/tap behavior prove difficult to use (mobile, shake fingers, Rhode Island, ...).

Per #62 clicking a state will also trigger this.

In both cases, the intent is to call `selectState()` to show a popup on the state, with details about the bias or data.

- [x] state name
- [x] bias percentage absolute value with a % sign and party, e.g. **+17% R**
- [x] narrative version including quantile: "this plan is more biases toward R than X% of plans analyzed"
- [x] styling, font, color, ...

**Comment by danrademacher** [comment]
Need a version of this that works on desktop and mobile without being the full-screen lightbox that takes over on any click.

Here's a rough mobile mock:
![image](https://user-images.githubusercontent.com/1423200/34392868-c5684492-eb03-11e7-901e-5566626f3531.png)

And less ideal desktop:
![image](https://user-images.githubusercontent.com/1423200/34392873-cc7fec30-eb03-11e7-9726-72d1f288e64b.png)

These are in XD v9 for refinement by @tsinn, then we need to figure out if they are feasible within Highcharts.

**Comment by tsinn** [comment]
Easy option that styles the modal Greg has in place

**Comment by danrademacher** [comment]
Looks and works pretty well now.

**Comment by danrademacher** [comment]
Looks great, but it shouldn't block interaction with the rest of the page. Let's just have it appear in front of the map itself, just like it does, but not block the page UI (scrolling, clicking other things). 

I assume we should be able to make the thing appear as a modal _only within_ `<div id="map"></div>`. That would also likely result in better placement on top of the map on mobile.

**Comment by gregallensworth** [comment]
467d862 is a complete refactor os the stateinfo popup. This being a modal, it's normal for it to block other action on the page (even if you turn the modal's background transparent). As such, I had to create a new DIV and merge in the styles, then put in a series of breaks and positioning code to try to make the popup appear at an appealing location on a variety of screens.

What I have in place works well for my testing so far, but really should be tested more thoroughly on a variety of devices. Now that the UI isn't blocked, expectations may change as far as the popup not touching other UI elements, not obscuring the title, etc.

**Comment by danrademacher** [comment]
Reviewed on many screensizes and browsers. Looks good and behaves as expected.
