### ISSUE TITLE
CSV data notes for the spreadsheet

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#64]
Some inconsistencies and issues encountered when working with the US House and State House CSVs so far.

### Relevant to the front page and national bias map

- [x] State House, the `bias` field has an extra space: `bias `
  * As such, it does not match up as "bias"
  * Suggest adjusting the columnheading
- [x] The `stpost` field is used as the key to connect a state to the map. US House had this named `state` instead
  * Please change the column name to `stpost`

### Relevant to the state details

The fields are not very consistent at all between US House and State House, which should mitigate expectations of what can be done on the state page for the different district types. Example: State House lacks the wasted-vote columns and total-vote columns, which would be used for charting.

Are state details pages meant to use only US House?

**Comment by danrademacher** [comment]
Let's just have the exact same schema for both views. I made new Production data sheets that pull from live data and transform into the same schema:
`us_house_production`: https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=1340994475
and
`state_house_production`:
https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=1167907324

You will see empty fields for all the Wasted Votes in State House. Let's just assume that if those fields are empty, that chart doesn't show. The state page works fine without it, though it is high impact, so good to have it on US House, which is the default view

**Comment by danrademacher** [comment]
Both datasets now have same schema and as far as I can see, this issue is resolved.
