### ISSUE TITLE
URL routing and params for state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#65]
We need to plan for URL routing like `planscore.org/northcarolina` for state pages.

We might also need to have stateful URLs for:
* House Level
* Election year
* Active metric tab

Might need to split this into 2 issues, for routing and params. For routing, I believe that desired solution is actually a set of build artifacts with static HTML for each state page in a folder named with that state's name, as opposed to a Javascript URL routing engine, but we might need to revisit that.

**Comment by migurski** [comment]
How about `/NC/NC0.0/House/2016/#EG` for a hierarchy?

**Comment by danrademacher** [comment]
That's a nice URL, though the plan seems only for emphasis. Every election year is by definition part of a single plan, so all we need is the year to know the plan. `/NC/House/2016/#EG` would work just as well and maybe be clearer to people.

But on tech side: Assuming your `/` and `#` are representative of an actual URL, that sounds more like a Javascript router than a bunch of static files, right? 

I say that because we don't want the page reloading every time someone changes US House to State House or picks a different year in the timeline, and even so I don't understand how we'd do that without a ton of duplicate static files in many nested folders.

If we want a little of both, seems we'd need to have a plain old folder `/NC` with an `index.html` and then a JS-parsed URL more like `/NC?plan=NC0.0&house=us&year=2016&metric=EG`. That would sacrifice human-readability of the URL to maintain overall simplicity of the site and not bring in overhead of a sitewide JS router.

Could be something I'm missing here. I usually leave route/param implementation to Greg and just specific what needs to be URL-able in some way.

**Comment by gregallensworth** [comment]
Beyond this is also URL routing for the peripheral pages to be linked from the top nav, e.g. About, Score Yours, and so forth. Whatever system we come up with wouldn't be specific to states, but they would be a special case of pages that look better as `/someurl/` than as `/someurl.html`

**Comment by gregallensworth** [comment]
2072088 creates a mechanism for loading *partial views* into the HTML output files when `npm run build` is used. This allows a shared `navbar.js` to define the navbar and then interpolate it into all generated static .html documents.

**Comment by gregallensworth** [comment]
All set here.

The loading of URL params for a specific district type and/or year, concerns URL params which is different than routing, e.g. `#ushouse-2016`

- [ ] front page, selecting year or district type, changes a hash e.g. `#ushouse-2016`
- [ ] front page, on load check hash, select that year + district
- [ ] state page, selecting year or district type, changes a hash e.g. `#ushouse-2016`
- [ ] state page, on load check hash, select that year + district

**Comment by migurski** [comment]
Say more about the JS router so I can understand the tradeoffs?

I've been thinking of the output site as primarily static, with a hierarchy of HTML files generated from underlying data and separate documents for each combination of states, plans, years, and houses. I can imagine a role for the browser history API and other similar things but having the sidebar timeline implemented as regular links from page to page seems fine as well.

**Comment by gregallensworth** [comment]
There is no JS router. The home page **/home/**resides under the `home/` folder, the **/texas/** URL is served from the `texas/` folder, and so forth.

This is described in detail here:  https://github.com/PlanScore/PlanScore/tree/gh-pages#the-state-pages-are-special

Within a page, the selection of year+districttype is represented in a hash `#1982-ushouse` This is updated when selections are made, and are parsed when the page is loaded.

The statistical content of the pages, is dynamically generated from the CSVs. Most of the statistics for the state pages are from the same CSV which powers the front page: number of plans and years, so would already be in browser cache if they had visited the front page (and vice versa, if they go from any one state to another, or to home). As such, loading speed is really quite nice.

**Comment by danrademacher** [comment]
To be clear, JS router discussion was my speculation on how we might achieve something. Then Greg came up with a better solution and implemented yesterday. We'll review on our call later today

**Comment by gregallensworth** [comment]
As of fdb6105 the state pages also set hash params when district/year are changed, and will load those hash params on page load. Issue #72 covers the actual functionality, but the hash save/load behavior is working per this issue #65

**Comment by gregallensworth** [comment]
Per chat today: Reorganize the `npm run build` process, so build artifacts go into a separate output folder from these sources. It would be *these* files which get uploaded as the static website.
