### ISSUE TITLE
Use data for North Carolina to test State Page Map

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#67]
Will be needed for Greg to build out first state page

**Comment by MaiannaVoge** [comment]
@gregallensworth 
Test round of NC1 (plan enacted in 1972), with relevant election results as attributes: P:\proj_p_s\Planscore\data\District_Geometries\North_Carolina\joined\NC1_joined.json

_DemPct_72_ = Percent of the vote that went to Democrats, by district, in 1972 election
_Winner_72_ = Winner of election by district in 1972 election, coded as D for Democrat and R for Republican
_Contest_72_ = True/False whether the election in that year/district was contested 

Let me know how this format works for you, working up the rest for North Carolina now.

**Comment by MaiannaVoge** [comment]
And here are the rest, @gregallensworth: 

P:\proj_p_s\Planscore\data\District_Geometries\North_Carolina\TopoJSON

Not sure why they are all wildly different in size. I ran them each through Mapshaper to get TopoJSON in the same way. I can simplify geometry in the future, just wanted to get these to you ASAP today.

**Comment by danrademacher** [comment]
Mike located the 2016 shp for NC, now linked in this line of the source sheet:
https://docs.google.com/spreadsheets/d/1qmm21sK_sCt-S31ug3OYPjmW_A1XgEg3jrKYlvaoUjE/edit#gid=290822865&range=303:303

**Comment by MaiannaVoge** [comment]
@danrademacher all the other North Carolina plans have the coastline cut out, but this new 2016 one doesn't, so it will look strange when we jump to 2016. I found a similar version of the 2016 plan from the Census, ok if I switch to that?

**Comment by danrademacher** [comment]
Yes, that sounds reasonable!

**Comment by MaiannaVoge** [comment]
Done: P:\proj_p_s\Planscore\data\District_Geometries\North_Carolina\TopoJSON\NC5.1_joined.json

**Comment by gregallensworth** [comment]
Summarizing scope per conversation today:

- [ ] TopoJSON file containing each plan's geometry but only minimal attributes such as district name

- [ ] CSV of election results + "plan winners" of locked-in districts

- [ ] Basic leaflet map, controls and basemaps TBD
  - [ ] one fixed basemap for simplicity?
  - [ ] ZoomBar with home control

- [ ] loading of appropriate TopoJSON file to display geometries
  * "Election mode" - find the plan for the given year, load that *geomtype-PLAN.json* file
  * "Plan mode" - load that *geomtype-PLAN.json* file

- [ ] classification & color
  * "Election mode" - **winner** field, D=blue R=red
  * "Plan mode" - **winner_plan** field, D=blue R=red X=tbd crosshatch?

**Comment by danrademacher** [comment]
OK, results table ready for CSV download here: https://docs.google.com/spreadsheets/d/1UkXOOXGLSoRjvpGj1eI5oTaMMIbo8jdevLzbDGuUU0E/edit#gid=1827372070

**Comment by gregallensworth** [comment]
Some examples of the colors:

![image](https://user-images.githubusercontent.com/3117633/34587527-8e94971c-f15d-11e7-8498-338e374b7143.png)


![image](https://user-images.githubusercontent.com/3117633/34587549-9c37abca-f15d-11e7-9c26-03445799d924.png)




The red and blue are the same red and blue used throughout the site, with a `fillOpacity: 0.2` applied.

The crosshatch is an image fill using `/images/mapfill_nodata.png`

**Comment by gregallensworth** [comment]
Got this all working per current spec. **Note** that polygon data exist only for North Carolina US House at this time, so that's the limit of testing. **Note** that all elections for North Carolina have data for all districts (no nodata conditions for any specific year).

### Simple blue and red election outcome

http://local.planscore.info:8000/north_carolina/#!1990-election-ushouse

![image](https://user-images.githubusercontent.com/3117633/34587771-950c912a-f15e-11e7-8a29-e1ba265a0032.png)

### Plan Outcome with a mix of D/R/neither

http://local.planscore.info:8000/north_carolina/#!1990-plan-ushouse

![image](https://user-images.githubusercontent.com/3117633/34587798-b0db1200-f15e-11e7-9f18-f2f9742de0d4.png)

http://local.planscore.info:8000/north_carolina/#!2012-plan-ushouse

![image](https://user-images.githubusercontent.com/3117633/34587817-c06b5f04-f15e-11e7-803a-d051a21606d9.png)

**Comment by danrademacher** [comment]
Awesome! Let's let Tim take a pass at the opacities border treatments.

**Comment by gregallensworth** [comment]
A new batch of data. Some new URLs, of the many which are now functional:

https://planscore.org/texas/#!1990-plan-ushouse
https://planscore.org/texas/#!2000-plan-ushouse
https://planscore.org/florida/#!1976-plan-ushouse
https://planscore.org/alabama/#!2006-plan-ushouse
https://planscore.org/washington/#!1996-plan-ushouse
https://planscore.org/pennsylvania/#!2006-plan-ushouse
https://planscore.org/missouri/#!2006-plan-ushouse
https://planscore.org/virginia/#!1986-plan-ushouse

**Comment by gregallensworth** [comment]
Some new map changes:

- [ ] see about retina-compliant tiles at 2X
- [ ] replace the labels layer with *Toner* labels; nicer than Positron

**Comment by migurski** [comment]
I’m seeing some odd behavior with the new 2x tiles on the state pages. It appears as though they're being requested at the wrong zoom level, leading to labels that are much too small? Current view of https://planscore.org/north_carolina/#!2016-election-ushouse:

<img width="864" alt="screen shot 2018-01-05 at 11 57 02 am" src="https://user-images.githubusercontent.com/58730/34625956-9a14485a-f20f-11e7-94b3-e0a3d3851333.png">

Retina labels should look like this:

<img width="1155" alt="screen shot 2018-01-05 at 11 57 58 am" src="https://user-images.githubusercontent.com/58730/34625988-b6e85d18-f20f-11e7-8a94-128f16745675.png">

Here’s the code generating the labels on the second map: https://github.com/PlanScore/PlanScore/blob/2621ae9db/planscore/website/static/plan.js#L430-L456

**Comment by migurski** [comment]
The text looks great now!

<img width="864" alt="screen shot 2018-01-05 at 4 05 32 pm" src="https://user-images.githubusercontent.com/58730/34633644-499dec6e-f232-11e7-82cd-76018fc0277f.png">

**Comment by danrademacher** [comment]
We still have #101 for styling of hashed fill. Looks like the rest of this is done. I'll open a data issue for pending state-level geometry

**Comment by tsinn** [comment]
New mapfill_nodata.png added to images directory for hashed fill. Also referenced in #101.
