### ISSUE TITLE
Page: Score a Plan

### ISSUE THREAD

**Issue by gregallensworth** [PlanScore/PlanScore#69]
The **Score a Plan** link in the top nav, goes to a new page at `/scoreyourown/` This page needs copy.

**Comment by danrademacher** [comment]
Replaced by a page Mike controls. We can remove `scoreyours` from the code base and replace all links to PlanScore.org/uploadplan.html

**Comment by danrademacher** [comment]
Oops, make that https://planscore.org/upload.html

**Comment by migurski** [comment]
I made this change (along with mostly copy edits) in https://github.com/PlanScore/PlanScore/pull/137

**Comment by danrademacher** [comment]
Ah great, and I see both in nav and side bar.
