### ISSUE TITLE
Site footer should be at bottom of page, not bottom of window

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#71]
Currently, the footer is pinned to the bottom of the window, which occludes main page content on smaller screens. Should just be at the bottom of page content, buried under scroll on smaller screens.

Here's 1024 by 768 currently:
![image](https://user-images.githubusercontent.com/1423200/34232469-42ee3c38-e595-11e7-953b-0a218f36b452.png)

vs desired:
![image](https://user-images.githubusercontent.com/1423200/34232503-63301fe8-e595-11e7-89c9-4b5ae1c64ccf.png)

**Comment by gregallensworth** [comment]
Done. The footer now blends in with the real background, to produce the "stretched to bottom" effect when there is less content than screen height.

![image](https://user-images.githubusercontent.com/3117633/34235355-03bdc888-e5a6-11e7-819e-8fdddfe3531a.png)
