### ISSUE TITLE
District picker style updates

### ISSUE THREAD

**Issue by tsinn** [PlanScore/PlanScore#74]

**Comment by gregallensworth** [comment]
Noted an issue on small screens, that the buttons don't stay the same height when their text line-wraps.

The following were noted around 500px-ish width.

![image](https://user-images.githubusercontent.com/3117633/34279203-468381d0-e664-11e7-86db-da81328eadc2.png)

![image](https://user-images.githubusercontent.com/3117633/34279212-55c1128e-e664-11e7-9e08-68edac9b44e0.png)



I would suggest a media query maybe, to force these to stack on small enough screens?
```
@media max-size 550px
#boundarypicker > div {
  width: 100%;
}
```

**Comment by danrademacher** [comment]
Stacking nicely:
![image](https://user-images.githubusercontent.com/1423200/34464846-92517a50-ee47-11e7-8c77-14017e9e8970.png)
