### ISSUE TITLE
Insert OG and Twitter Card content in PlanScore/_pagestarter/index.src.html

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#88]
Current PlanScore has the following:
```
<meta property="og:title" content="PlanScore" />
--
  | <meta property="og:type" content="website" />
  | <meta property="og:url" content="https://planscore.org" />
  | <meta property="og:image" content="https://planscore.org/static/opengraph-image.jpg" />
  | <meta property="og:description" content="PlanScore is a first-of-its-kind gerrymandering scoring service for new district plans, allowing users to upload maps and instantly receive projected data about their partisan consequences." />
``` 

For State Pages, per #80, let's plan on inserting the STATE NAME in the OG tags

**Comment by danrademacher** [comment]
Working, but text is a bit too long:

Home:
![screen shot 2017-12-27 at 1 57 22 pm](https://user-images.githubusercontent.com/1423200/34394436-f697f9c2-eb0d-11e7-8c06-42195fc1377e.png)

State Page:
![screen shot 2017-12-27 at 1 58 26 pm](https://user-images.githubusercontent.com/1423200/34394448-0b8d0598-eb0e-11e7-90c9-680926de4d87.png)

We'll need to update the OG image with something new. And would be awfully nice to generate something per state...

**Comment by migurski** [comment]
Per-state would indeed be amazing.

**Comment by danrademacher** [comment]
OK, I have a process using Adobe's "DATASETS" function to output dynamic per-state images with text driven by the gSheets data. Sized to 1200x630, per [this documentation from FB](https://developers.facebook.com/docs/sharing/best-practices/). 

We might want a better call to action on all of these, though variants with some data seem reasonable as is. no data sets could use a better CTA, though I am not quite sure what that CTA should be (like what data could people supply that would help, if they even could, or if the state is out because of problems with its history that make it incompatible with the analyses we're using).

Examples:

### CONGRESS ONLY
![az-01](https://user-images.githubusercontent.com/1423200/34464876-b34a78e6-ee48-11e7-8493-4cee6387947e.jpg)

### CONGRESS + STATE, same number of plans
![al-01](https://user-images.githubusercontent.com/1423200/34464870-9786739e-ee48-11e7-8d9b-55ad070269ad.jpg)

### CONGRESS + STATE, different number of plans
![co-01](https://user-images.githubusercontent.com/1423200/34464877-b622749c-ee48-11e7-8753-8c932ff6a7d6.jpg)

### STATE ONLY
![wy-01](https://user-images.githubusercontent.com/1423200/34464884-66ac9b3a-ee49-11e7-8c47-304efc5a487e.jpg)

### No data
![la-01](https://user-images.githubusercontent.com/1423200/34464878-b9f635ae-ee48-11e7-8d68-e7609d2a1489.jpg)

**Comment by danrademacher** [comment]
these are all being named with the same `state_name` slug we're using for the folders, so we should be able to add a hard-coding in of the OG image to the `npm run states` action to make sure these get connected to their pages

**Comment by danrademacher** [comment]
Remaining TODOs here:
- [ ] Default OG image for all non-state pages
- [ ] Finalize language for per-state OG images

**Comment by danrademacher** [comment]
Change language to mention partisan gerrymandering, drop the data points.

**Comment by danrademacher** [comment]
Better, though image is super small in Slack unfurling. Based on [this](https://medium.com/slack-developer-blog/everything-you-ever-wanted-to-know-about-unfurling-but-were-afraid-to-ask-or-how-to-make-your-e64b4bb9254), looks like we can just add

```<meta name="twitter:card" content="summary_large_image">```
