### ISSUE TITLE
Front-page map: Use Times Approximate

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#89]
Ultimately, we need to replace home-page map geometry with Times Approximate (https://giscollective.s3.amazonaws.com/projectlinework/times-approximate.zip).

The supplied GeoJSON and SHP files have all states + PR in their real locations. We need to:
- [x] Remove PR
- [x] Place Alaska and Hawaii below the continental US
- [x] Rewire the small-state callouts
- [x] Rewire interactivity

It looks like it _might_ be expedient to simply fork our own version this file, change settings at the top and replace the geometry, which would preserve all downstream interaction and code as is:
https://code.highcharts.com/mapdata/countries/us/custom/us-small.js

Looks like there are various projection settings and transforms at the top, and each state in the JS is a standalone GeoJSON element, where small Eastern states have their callout boxes built in, like this:
![image](https://user-images.githubusercontent.com/1423200/34364252-deaf905c-ea38-11e7-9122-8434f3fe8ec1.png)

If reverse-engineering the existing NE-based Highcharts file is a bear, the other option is to use the documented method of using custom geojson, as here:
https://www.highcharts.com/docs/maps/custom-geojson-maps

And then re-engineer the callouts and interactions.

**Comment by danrademacher** [comment]
Before we do this, we need to assess #63 and make sure we can achieve what we need to within Highcharts.

**Comment by danrademacher** [comment]
Notes from Slack today:

Overall we're trying to balance the ease of Highcharts vs. need for some further customization per client feedback. Boils down to two things:

1. Replace Highcharts geom with better geom (this looks like it might be completely manageable by Tim and MM)

2. Instead of modal and can we feeding the same look and content into another div on the page (ie, one that doesn’t take over the page and prevent interaction elsewhere).

**Comment by danrademacher** [comment]
This should just need quick review of best way to include our version of `us-small.js` in final build, and then merge.

**Comment by gregallensworth** [comment]
All set. Merged that PR, then shifted a few files around to expected locations.

### After, note slightly curved shapes

![image](https://user-images.githubusercontent.com/3117633/34541844-bb604338-f08e-11e7-9597-e1c6ee8feeee.png)



### Before, note slightly more jagged shapes

![image](https://user-images.githubusercontent.com/3117633/34541865-c95d1bfa-f08e-11e7-8b0b-7df5582bf622.png)

**Comment by gregallensworth** [comment]
Reopen for a data fix.

The right-side boxes are part of the multipolygons for their respective states. The positioning of them is a bit weird, touching Maine and leaving empty space. Shift them downward a bit, so the top box is about the northernmost party of Massachusetts, and the bottom box ends about a box height's north of the tip of Florida.

**Comment by migurski** [comment]
Need me to do this?

**Comment by gregallensworth** [comment]
I'll give it a try, and will let you know if it's beyond me. Thank you for asking.

**Comment by migurski** [comment]
Great! I noticed that for each of the relevant states ('Vermont', 'New Hampshire', 'Massachusetts', 'Rhode Island', 'Connecticut', 'New Jersey', 'Delaware', 'Maryland', 'District of Columbia'), the rectangle part was the first part in the MultiPolygon.

**Comment by gregallensworth** [comment]
Updated version:
* moved the New England callout boxes downward, for better vertical centering
* removed extraneous attributes; brought file size from 50 KB to 32 KB
