### ISSUE TITLE
Refine site-wide max-width

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#91]
Per feedback from Mike, let's consider stepping down our main column sizing a bit sooner so we don't get too crammed in the middling widths.

The 1199/1200 break looks pretty good as our widest screen size (any wider and line lengths get too long for reading):
![image](https://user-images.githubusercontent.com/1423200/34367190-19c71520-ea5c-11e7-9d21-032461869022.png)

But then as we scale down, things get squeezed before they drop down again. This is at 1019px:
![image](https://user-images.githubusercontent.com/1423200/34367249-f3e4af56-ea5c-11e7-92ec-04cd88c56723.png)

Then we break again at 991px. I'd do that break at 1024.

Thoughts?

**Comment by migurski** [comment]
One thing not visible in the screens above is the high number of words per line at the wider breaks. For the smaller text in the homepage metrics boxes this is more pronounced. A narrower page will make reading slightly easier, and may unify the visual appearance of the wide year picker with the narrow US states map.
