### ISSUE TITLE
Larger hit areas on State Page election picker and home page state list

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#93]
Similar to changes already made on the home page timeline

Election State list hit areas

Bigger and highlight as you are rolling around

And make the list items on the home page light up and take a whole row and column regardless of state name length

**Comment by danrademacher** [comment]
Clarifying graphic. Looks the same but hit areas like this:
![image](https://user-images.githubusercontent.com/1423200/34496102-14c72ab4-efad-11e7-9d0d-2def566712be.png)

**Comment by gregallensworth** [comment]
Here we go:

![image](https://user-images.githubusercontent.com/3117633/34496360-203f0d0c-efae-11e7-8c3c-2fa256608c8c.png)


The background color is plain old SCSS `.states-listing a:hover background-color`

I added some padding to each `a` element, so as to achieve two goals: a) increase the hit box for each state; and also b) the highlighted area doesn't run up against the edge of the swatch.

**Comment by gregallensworth** [comment]
I think this is what was requested fr the states page yearpicker:

![image](https://user-images.githubusercontent.com/3117633/34496931-57047f96-efb0-11e7-823b-87750cfc20ed.png)


* There is a `:hover` CSS effect to give it the `background-color: #f2f2f2`.
* I added some padding top and bottom to increase hitbox size. *Note* if we keep adjusting this, that this padding requires tweaking the settings for the background-image to keep it stretched properly.
