### ISSUE TITLE
Plan vs. Election view of state page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#94]
On the state page, we have a lack of clarity whether you are looking at an Election or a plan
Example: https://planscore.org/arizona/#!2016-ushouse

The page will looks different depending on whether a PLAN or an ELECTION is selected.

**Comment by danrademacher** [comment]
Here is a pretty complete breakdown of all the values on the page, for PLAN vs. ELECTION. I'll file separate issues for the MAP and the plan/election selector.

## PLAN

TITLE:
`plan_minyear`-`plan_maxyear` Redistricting Plan

### EG Tab
+`abs(eg_adj_avg)`% Republican|Democrat 
Republicans|Democrats needed `abs(eg_adj_avg)`% fewer votes to win their `seats_r_plan`|`seats_dem_plan` of `seats_plan` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-eg_avg_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `eg_adj_avg`

Wasted votes:
`wasted_dem_plan`
`votes_dem_plan`
`wasted_rep_plan`
`votes_twop_plan`

### MMD Tab
+`abs(mmd_adj_avg)`% Republican|Democrat 
Republicans|Democrats needed `abs(mmd_adj_avg)`% fewer votes to win their `seats_r_plan`|`seats_dem_plan` of `seats_plan` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-mmd_avg_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `mmd_adj_avg`

### PB Tab

+`abs(bias_adj_avg)`% Republican|Democrat 
Republicans|Democrats needed `abs(bias_adj_avg)`% fewer votes to win their `seats_r_plan`|`seats_dem_plan` of `seats_plan` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-bias_avg_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `bias_adj_avg`

## ELECTION

TITLE:
`plan_minyear`-`plan_maxyear` Redistricting Plan: `year` Election

### EG Tab
+`abs(eg_adj)`% Republican|Democrat 
Republicans|Democrats needed `abs(eg_adj)`% fewer votes to win their `seats_r`|`seats_dem` of `seats` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-eg_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `eg_adj`

Wasted votes:
`wasted_dem`
`votes_dem`
`wasted_rep`
`votes_twop`

### MMD Tab
+`abs(mmd_adj)`% Republican|Democrat 
Republicans|Democrats needed `abs(mmd_adj)`% fewer votes to win their `seats_r`|`seats_dem` of `seats` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-mmd_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `mmd_adj`

### PB Tab

+`abs(bias_adj)`% Republican|Democrat 
Republicans|Democrats needed `abs(bias_adj)`% fewer votes to win their `seats_r`|`seats_dem` of `seats` seats.

How Does This Plan Compare?
This plan is more biased toward than `(1-bias_percentrank)*100`% all of the enacted plans we've analyzed nationwide.

Bell curve marker placed based on `bias_adj`

**Comment by danrademacher** [comment]
Need to revise the above to account for percentrank should use ABS() and not refer to party

**Comment by gregallensworth** [comment]
Good chat today clarifying this for me. To break it down into a to-do list:

- [ ] mobile yearpicker needs rework, to specify whether one wants the ELECTION data or the PLAN data displayed
- [ ] desktop (bead chain) yearpicker, same as above as to changing year and election/plan details
- [ ] implementation of all fields as described above

**Comment by gregallensworth** [comment]
98e159b -- the yearpickers (mobile + desktop) now call `selectElectionOrPlan()` which now supports a second param: election or plan. This is now stored as part of the `CURRENT_VIEW` state.

This lays the framework for the various updateStatsFromCsvContent() components to fill in the relevant stats from the election fields or plan fields.

**Comment by gregallensworth** [comment]
Per the above commits, the state page now shows the appropriate Election-level or Plan-level stats, depending on the selection. Testing should note / include the following:
* mobile year-and-plan picker, now that it has 2 entries per year
* desktop "beaded" year-and-plan picker, now that the grey dot and the black dot have different functions
* display of the title (indicating election year or not)
* display of the bell curves, "this is more biased %" text, count of seats, etc. in the tabs
* display of the "2 out of 3 metrics" summaries

**Comment by danrademacher** [comment]
Looks like the bell curves are not swapping out based on PLan vs Election for each metric:

![image](https://user-images.githubusercontent.com/1423200/34551900-a55468f0-f0d2-11e7-97bb-f1ade3d6a6d8.png)

Election is selected, but bg image is `/images/ushouse_eg_plan_curve.svg`, should be `/images/ushouse_eg_election_curve.svg`

**Comment by danrademacher** [comment]
OK, outcome of discussion with Mike just now:

At least for the time being, we need to disable Election views. But we can do that without any visual change to the page.

- [ ] Clicking any election enables that election's PLAN, so election views are no longer accessible through the UI
- [ ] Optionally we clear out the Election-level data from the site CSVs

But we leave the machinery in place in case we want to bring these back later.

**Comment by gregallensworth** [comment]
As of 310a5ce the desktop "beaded" year-picker, now selects the Plan when a Year is clicked.

* Links front home page to state page, use the `plan` link.
* States, desktop year picker now picks plan.
* States, mobile defaults to plan and has no mechanism to switch to election-year.
