### ISSUE TITLE
Finalize bell curves

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#97]
For outstanding issues on #72, we need SVG or PNG bell curves.

This folder contains an AI file, source PNGs from gSheets and test export SVGs:
https://drive.google.com/drive/folders/1Awfvm6DIos5NA5ENBDedlk9vuD4gFVLw

AI file contains the proper curves with a draft color gradient, but needs color finalization per #95  and then final size output.

Source charts are here:
https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=344536830

We need to make a similar set for State House and (if we get the data) State Senate

**Comment by migurski** [comment]
Is our curve actually a normal distribution? I seem to recall seeing a slightly bumpier one from Nick based on this data.

**Comment by danrademacher** [comment]
Hmm, good question.

I just dropped the Sheets-native histograms into the [Sheet with the bell curves](https://docs.google.com/spreadsheets/d/1eMwwL8eaxD3aAyiy410yt79Cik2GV31WrXWyzFsiSTs/edit#gid=344536830)

I can see that Normal Distribution definitely drops variability at the extremes. We probably need expert guidance here on how these curves should be made.

**Comment by migurski** [comment]
I'm unfamiliar enough with GDocs charts, but is it possible to make the bucket sizes more granular (0.02 or 0.01) and then interpolate between them?

**Comment by danrademacher** [comment]
That's easy to do:
![image](https://user-images.githubusercontent.com/1423200/34392469-1dfd53c0-eb01-11e7-8d8d-628c776aaaf2.png)

I meant more of stats expertise if we needed to use some unknown-to-me but well-respected *abnormal* distribution

**Comment by migurski** [comment]
The uptick at -0.2 feels like there should be something over there — maybe this could extend 0.1 past either extreme to clearly communicate that the whole thing is present?

**Comment by danrademacher** [comment]
Here they are with fewer bins, and one for PLANS, one for ELECTIONS:
![image](https://user-images.githubusercontent.com/1423200/34395533-d1367e12-eb15-11e7-80de-7a887e2aa785.png)

Per #94, we might need both. But it is hard to grok why the curves are so different. The peak of both tends slightly R butt he distribution is quite different

**Comment by danrademacher** [comment]
OK, we have a file that @tsinn can use for color testing per #95, here on Drive: https://drive.google.com/open?id=16GKUi9xCrqeHcjGjKiJD1B7XPJqFbw6H

I'm going to reference that file for color selection over there.

One of the curves is in place in the build as a test, but there's a fair bit more to do here:
- [ ] Finalize colors. That's part of #95 
- [ ] Confirm that we DO want to flip values end for end so that D = LEFT leaning and R = right leaning. 
- [ ] Clarify per #94 whether we want two different bells, one for Election and one for Plan
- [ ] Output the SVG assets of as many charts as we need
- [ ] Rework [this code](https://github.com/PlanScore/PlanScore/blob/gh-pages/_statetemplate/state_template.js6#L368-L379) to chart the actual metric for the PLAN or ELECTION, not the percentile, which we will use only in the text above the chart.

**Comment by danrademacher** [comment]
Min and Max values for new version of charts:

US House EG:
Min | -0.203
Max | 0.203

US House Mean Median:
Min. -0.1060091362
Max  0.1017622749

US House PB:
Min -0.2725428571
Max 0.25

State EG:
Min -0.137
Max 0.166

State MMD:
Min -0.0944124802
Max 0.07623086263

State PB:
Min -0.1902700474
Max 0.2449782744

**Comment by gregallensworth** [comment]
This should be all set now. The data range is used to position the black bar, and the proper SVG background is used based on the 3 metrics X 3 boundary types.

**Comment by danrademacher** [comment]
Let's have @tsinn refine styling here -- some notes:
- [ ] collision of curve and highcharts 
- [ ] height of plumbline to match height of curve
- [ ] maybe thinner plumbline?

**Comment by danrademacher** [comment]
Corrected MIN and MAX for the DOMAIN of the chart areas, not the data itself. Turns out the domains are the same for each indicator across BOTH plan/election variable AND US House / State House variable.

US House EG:
Min -0.22
Max 0.22

US House Mean Median:
Min -0.11
Max 0.11

US House PB:
Min -0.3
Max 0.3

State EG:
Min -0.22
Max 0.22

State MMD:
Min -0.11
Max 0.11

State PB:
Min -0.3
Max 0.3

**Comment by gregallensworth** [comment]
5f314af brings a near-total do-over of the bell curve charts.

* The DIV is still a DIV and the curve is still a background-image. The choice of image is still driven by CSS utility classes.
* The image will not stretch nor scale properly to always fill the responsive-width area; they just can't do that. Instead, the bell-chart DIVs now have a fixed width of `250px` so the image can fill a known area properly.
* The marker line has been reworked entirely. It is no longer a Highchart but a positioned DIV, with its `left: X%` determined by the score and the spread of scores depicted in the picture. As a result, it can now be more precisely positioned.

Result is a faster responsiveness, and guarantee that the image and markline will stay positioned properly on all screen sizes.

**Comment by danrademacher** [comment]
Ugh these bell curves. Georgia in 1972 was _super_ Democratic:
![image](https://user-images.githubusercontent.com/1423200/34598116-c2f67bfa-f19f-11e7-9358-b663a0b0ef6a.png)

https://planscore.org/georgia/#!1972-election-ushouse

(looking at the unfolding of the Southern Strategy in these maps is weirdly fun, and discouraging)

**Comment by danrademacher** [comment]
Washington in 1978 is the most extreme:
![image](https://user-images.githubusercontent.com/1423200/34598211-2dfd3966-f1a0-11e7-96bc-625a5f5dc6fc.png)

https://planscore.org/washington/#!1978-election-ushouse

I thought bell curves based on plan Min and max would work. They do show outliers...

**Comment by gregallensworth** [comment]
The existing domains for X axes, were not in fact the most extreme values seen? That's good information, and capping them at 0 and 100 would be quite easy as did the prior version.

**Comment by danrademacher** [comment]
I was using Max and Min at the plan level, which are averages of the Election data. Some of the latter, not surprisingly, exceed the averages.

So a downstream consequence of #94

**Comment by gregallensworth** [comment]
Confirmed that the states min/max scores are not in fact the min & max.

16d78f6 enforces a range of 0 to 1. This will serve for mistaken X domains, for plans or elections outlying previous assumptions, and (some day) for custom plans which happen to be outliers from prior ranges.

**Comment by danrademacher** [comment]
Let's use CSS to add these markers:

Left side: "+"&MAX&"% D"
Mid: "Balanced"
Max:  "+"&MAX&"% R"

**Comment by danrademacher** [comment]
Here's the idea:
![image](https://user-images.githubusercontent.com/1423200/34732584-8c7a6252-f51a-11e7-849a-15201984dffb.png)

**Comment by gregallensworth** [comment]
These "axis labels" are now in place as depicted above.

![image](https://user-images.githubusercontent.com/3117633/34735651-06c1b04c-f525-11e7-9c81-a673e400aeea.png)

**Comment by danrademacher** [comment]
What do you think about adding that "bonus" "This Plan" label from the second PNG above? Too complex?

![image](https://user-images.githubusercontent.com/1423200/34732680-cdcd8f54-f51a-11e7-9e62-e8761a5aa693.png)

**Comment by gregallensworth** [comment]
First version, smaller font with line wrapping:

![image](https://user-images.githubusercontent.com/3117633/34739433-1e562826-f531-11e7-9f6d-b3cca4b73180.png)




![image](https://user-images.githubusercontent.com/3117633/34739452-2fd7183a-f531-11e7-80d8-04432c73b2a4.png)





![image](https://user-images.githubusercontent.com/3117633/34739493-4f63962e-f531-11e7-82df-ec0f48deb742.png)

**Comment by gregallensworth** [comment]
Second draft, more similar to that depicted: no text wrapping, larger font. Looks quite good here, though can extend past the edge of the tab-content box (not a problem, but a cosmetic oddity).


![image](https://user-images.githubusercontent.com/3117633/34739671-d8f89c9a-f531-11e7-8b91-3887ef94915e.png)



![image](https://user-images.githubusercontent.com/3117633/34739719-0264c1c6-f532-11e7-90fd-bfdb105733e4.png)

**Comment by migurski** [comment]
It does look a little odd extended past the end of the box like that. If it’s possible to fix, it seems worth doing. On the whole, these additions to the histograms are a massive and beneficial improvement.

**Comment by gregallensworth** [comment]
Here we go with some handling of far-right and far-left cases.

![2018-01-09 13_12_10-planscore __ texas](https://user-images.githubusercontent.com/3117633/34743543-eaf6a376-f53e-11e7-8c72-e13b9f44b099.png)
![2018-01-09 13_12_21-planscore __ texas](https://user-images.githubusercontent.com/3117633/34743544-eb142482-f53e-11e7-89c8-d7c5b0e027c4.png)
![2018-01-09 13_12_33-planscore __ texas](https://user-images.githubusercontent.com/3117633/34743545-eb44d226-f53e-11e7-928e-5d503bf21f6e.png)
