### ISSUE TITLE
Create UI Pattern Page

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#98]
We need to develop a page of the typical UI patterns for Mike to use elsewhere on the site. 

Here's a Mock (in XD v9) that shows the range of what we need, though styles in some areas need refinement from @tsinn:

![patternlibrarypage](https://user-images.githubusercontent.com/1423200/34390497-eef1e25a-eaf4-11e7-983b-2c2988e80b1d.png)

**Comment by danrademacher** [comment]
I'll do:
- [ ] add page
- [ ] block out HTML elements

Then handoff to Tim for refinement

**Comment by danrademacher** [comment]
Per discussion with Mike this AM, Tim is working on SCSS/CSS for unstyled items here, and then Mike and Greg will connect on actual needs for JS pieces, which will be minimal or maybe none.

**Comment by danrademacher** [comment]
all image links need to be absolute here longer term. If we make that universal, I wonder how we manage local testing of revised styling and BG images.

**Comment by danrademacher** [comment]
@gregallensworth here's another item you could take a look at -- some systematic way to make image links absolute in built HTML and CSS? @migurski hand edited our template so he could work with it for now, but eventually the idea is someone could use the source code of this page, https://planscore.org/patternlibrary_htmltemplate/index.html, and associated CSS, to make a compliant PlanScore page on any server. Which I assume means all BG images and other items need absolute paths?

**Comment by gregallensworth** [comment]
I have just been using URIs with paths, e.g. `/images/ushouse_eg_plan_curve.svg`

If one wants to otherwise link directly to images etc. they could just use the full URL, starting with *https://planscore.org/* e.g. *https://planscore.org/images/logo.svg*

In the case of CSS, these are interpreted as relative to the stylesheet, e.g. `background-image: url(/images/ushouse_eg_plan_curve.svg);` when loaded from *https://planscore.org* is presumed to be **https://planscore.org/images/ushouse_eg_plan_curve.svg**

Maybe if I saw a problematic page in context, I could come up with some more concrete idea of the problem I'm trying to solve?

**Comment by migurski** [comment]
Linking to the full URL works well. I’ve already made this change in one spot, and I can just keep doing it?

**Comment by gregallensworth** [comment]
From "third party" pages, linking to the URLs using "plain old absolute paths" seems the right way to do it, as well as the simplest. That's what I would recommend for loading the stylesheets, for linking to pages, for including images, etc.

**Comment by danrademacher** [comment]
My only thought for improvement here for future use, vs immediate need, would be to make the `<img>` paths in the header and footer absolute, so if you save source on https://planscore.org/patternlibrary_htmltemplate/index.html, it "just works". Obviously easy enough for Mike to replace those for his needs. And if that's good enough, we can close this out.

**Comment by danrademacher** [comment]
Histograms on PatternLibrary page as JS function
* move CSS to sitewide if not already
* move JS to sitewide if not already

Add to pattern library page with demo of how to feed it geog, metric, and metric value and get plumbline on the chart

**Comment by gregallensworth** [comment]
Created a publicly-exposed function in **sitewide.js** called `drawBiasBellChart()`

This is used to draw bellcharts.

For complete documentation and copy-paste HTML and JS code, see "Bias Scoring Histograms" section of the pattern library page.
