### ISSUE TITLE
Refine tab layout and other spacing issues on mobile view

### ISSUE THREAD

**Issue by danrademacher** [PlanScore/PlanScore#99]
Too tight/weird wrap:
https://xd.adobe.com/view/d60c26ff-6566-4b21-a3e4-5035b16d12aa/screen/1331970c-eb99-4880-937a-f10b4c08ded7/iPhone-6-7-8-1

**Comment by danrademacher** [comment]
Also on the mobile state view, and related to #100, is the collapsible view of the Plan/Year selector and mobile behavior we discussed to replace SELECT menu -- collapsible everywhere, default open on desktop but closed on mobile, selecting or plan or election on mobile also closes the panel

**Comment by danrademacher** [comment]
Still needs work on 320px / iPhone 5/SE:

Home:
![image](https://user-images.githubusercontent.com/1423200/34464855-deab3cf6-ee47-11e7-90ac-fbc087a92e14.png)

Sate:
![image](https://user-images.githubusercontent.com/1423200/34464856-e95338fc-ee47-11e7-9751-6e79032b440f.png)

closer on iPhone 6/7
![image](https://user-images.githubusercontent.com/1423200/34464859-001fa156-ee48-11e7-8e5e-ca4faf5511dc.png)

**Comment by gregallensworth** [comment]
Mean/Median is one word but on mobile we wish it were two words, so it would line-wrap.

d6f8f65 adds a new utility class which wraps a single space. This class is `display:none` except at tiny screens.

Result: The text reads "Mean/Median" with no visible space on large-enough screens, and reads "Mean/ Median" on tiny screens and thus gets line-wrapped nicely.

**Comment by migurski** [comment]
FYI, [`<wbr>` exists also](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr)!

**Comment by danrademacher** [comment]
huh, how'd I miss the `<wbr>` memo? Looks like it needs a workaround in IE? https://stackoverflow.com/questions/23756932/wbr-tag-doesnt-work-in-ie Though that's 2014, so maybe old news.

**Comment by danrademacher** [comment]
Looking good on those super narrow 320px screens:
![image](https://user-images.githubusercontent.com/1423200/34547598-253944c2-f0b1-11e7-8782-a52212397b6a.png)
